calculate_log_der_matrix – the SCATTERING code
calculate_log_der_matrix Subroutine
41 statements
Source File
public subroutine calculate_log_der_matrix(h, y_dim, tt_min, tt_n, tt_plus, r_n, r_plus, log_der_matrix)
calculates the log-derivative matrix from Eq. (6.29) called by numerov and log_derivative at the end of the propagation
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: h
step of the propagation
integer(kind=int32), intent(in) :: y_dim
dimension of the log-derivative matrix
real(kind=dp), intent(in) :: tt_min(y_dim,y_dim)
T-matrix at R_{max - 1}
real(kind=dp), intent(in) :: tt_n(y_dim,y_dim)
T-matrix at R_{max}
real(kind=dp), intent(in) :: tt_plus(y_dim,y_dim)
T-matrix at R_{max + 1}
real(kind=dp), intent(in) :: r_n(y_dim,y_dim)
R-matrix at R_{max}
real(kind=dp), intent(in) :: r_plus(y_dim,y_dim)
R-matrix at R_{max + 1}
real(kind=dp), intent(inout) :: log_der_matrix(y_dim,y_dim)
log-derivative matrix
Calls
Called by
Contents
Variables
a ab abc b bra c d de def e f g i j
Source Code
calculate_log_der_matrix
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: a(y_dim,y_dim)
real(kind=dp), public :: ab(y_dim,y_dim)
real(kind=dp), public :: abc(y_dim,y_dim)
real(kind=dp), public :: b(y_dim,y_dim)
real(kind=dp), public :: bra(y_dim,y_dim)
real(kind=dp), public :: c(y_dim,y_dim)
real(kind=dp), public :: d(y_dim,y_dim)
real(kind=dp), public :: de(y_dim,y_dim)
real(kind=dp), public :: def(y_dim,y_dim)
real(kind=dp), public :: e(y_dim,y_dim)
real(kind=dp), public :: f(y_dim,y_dim)
real(kind=dp), public :: g(y_dim,y_dim)
integer(kind=int32), public :: i
integer(kind=int32), public :: j
Source Code
      subroutine calculate_log_der_matrix(h,y_dim,tt_min,tt_n,tt_plus,r_n,r_plus,log_der_matrix)
         !! calculates the log-derivative matrix from Eq. (6.29)
         !! called by numerov and log_derivative at the end of the propagation
         !---------------------------------------------------------------------!
         real(dp), intent(in) :: h
            !! step of the propagation
         integer(int32), intent(in) :: y_dim
            !! dimension of the log-derivative matrix
         real(dp), intent(in) :: tt_min(y_dim, y_dim)
            !! T-matrix at R_{max - 1}
         real(dp), intent(in) :: tt_n(y_dim, y_dim)
            !! T-matrix at R_{max}
         real(dp), intent(in) :: tt_plus(y_dim, y_dim)
            !! T-matrix at R_{max + 1}
         real(dp), intent(in) :: r_n(y_dim, y_dim)
            !! R-matrix at R_{max}
         real(dp), intent(in) :: r_plus(y_dim, y_dim)
            !! R-matrix at R_{max + 1}
         real(dp), intent(inout) :: log_der_matrix(y_dim, y_dim)
            !! log-derivative matrix
         !---------------------------------------------------------------------!
         integer(int32) :: i, j
         real(dp) :: a(y_dim,y_dim), b(y_dim,y_dim), c(y_dim,y_dim),           &
            d(y_dim,y_dim), e(y_dim,y_dim), f(y_dim,y_dim), g(y_dim,y_dim),    &
            ab(y_dim,y_dim), abc(y_dim,y_dim), de(y_dim,y_dim),                &
            def(y_dim,y_dim), bra(y_dim,y_dim)
         !---------------------------------------------------------------------!
         log_der_matrix = 0
         !---------------------------------------------------------------------!
         do i=1,y_dim
            do j=1,y_dim
               a(i,j) = - tt_plus(i,j)
               b(i,j) = - tt_plus(i,j)
               c(i,j) = r_plus(i,j)
               d(i,j) = - tt_min(i,j)
               e(i,j) = - tt_min (i,j)
               f(i,j) = r_n(i,j)
               g(i,j) = - tt_n(i,j)
            end do
            a(i,i) = 0.5 + a(i,i)
            b(i,i) = 1. + b(i,i)
            d(i,i) = 0.5 + d(i,i)
            e(i,i) = 1. + e(i,i)
            g(i,i) = 1. + g(i,i)
         end do
         !---------------------------------------------------------------------!
         call invert_symmetric_matrix(b)
         call fill_symmetric_matrix(b, "u")
         call invert_symmetric_matrix(e)
         call fill_symmetric_matrix(e, "u")
         call invert_symmetric_matrix(f)
         call fill_symmetric_matrix(f, "u")
         !---------------------------------------------------------------------!
         CALL DGEMM('N','N',y_dim,y_dim,y_dim,1.0d0,&
                    a,y_dim,b,y_dim,0.d0,ab,y_dim)
         CALL DGEMM('N','N',y_dim,y_dim,y_dim,1.0d0,&
                    ab,y_dim,c,y_dim,0.d0,abc,y_dim)
         CALL DGEMM('N','N',y_dim,y_dim,y_dim,1.0d0,&
                    d,y_dim,e,y_dim,0.d0,de,y_dim)
         CALL DGEMM('N','N',y_dim,y_dim,y_dim,1.0d0,&
                    de,y_dim,f,y_dim,0.d0,DEF,y_dim)
        !----------------------------------------------------------------------!
         bra = abc - def
         !---------------------------------------------------------------------!
         CALL DGEMM('N','N',y_dim,y_dim,y_dim,dble(1.d0/h),bra,&
                    y_dim,g,y_dim,0.d0,log_der_matrix,y_dim)
         !---------------------------------------------------------------------!
      end subroutine calculate_log_der_matrix
Call graph
calculate_log_der_matrix calls invert_symmetric_matrix, fill_symmetric_matrix, dgemm
numerov calls calculate_log_der_matrix
scattering calls numerov