calculate_t_matrix – the SCATTERING code
calculate_t_matrix Subroutine
6 statements
Source File
private subroutine calculate_t_matrix(step_, coupling_matrix_, t_matrix_)
Calculates the T-matrix from the coupling matrix at grid point N: \(T_{\mathrm{N}} = h^{2}/12 W_{\mathrm{N}} \)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: step_
step of the propagator
real(kind=dp), intent(in) :: coupling_matrix_(:,:)
Coupling (W) matrix v
real(kind=dp), intent(inout) :: t_matrix_(:,:)
(output) T-matrix at grid point N
Called by
Contents
Source Code
calculate_t_matrix
Source Code
      subroutine calculate_t_matrix(step_, coupling_matrix_, t_matrix_)
         !! Calculates the T-matrix from the coupling matrix at grid point N:
         !! \\( T_{\mathrm{N}} = h^{2}/12 W_{\mathrm{N}} \\)
         !---------------------------------------------------------------------!
         real(dp), intent(in) :: step_
            !! step of the propagator
         real(dp), intent(in) :: coupling_matrix_(:,:)
            !! Coupling (W) matrix v
         real(dp), intent(inout) :: t_matrix_(:,:)
            !! (output) T-matrix at grid point N
         !---------------------------------------------------------------------!
         t_matrix_ = (step_**2.0_dp)/12.0_dp * coupling_matrix_
         !---------------------------------------------------------------------!
      end subroutine calculate_t_matrix
Call graph
initial_setup calls calculate_t_matrix
general_propagation_step calls calculate_t_matrix
numerov calls initial_setup, general_propagation_step, handle_final_propagation_steps
handle_final_propagation_steps calls general_propagation_step
scattering calls numerov