calculate_coupling_matrix – the SCATTERING code
calculate_coupling_matrix Subroutine
7 statements
Source File
private subroutine calculate_coupling_matrix(intermolecular_distance_, pes_matrix_, centrifugal_matrix_, coupling_matrix_)
Combines the contribution from the interaction potential, total and and internal energy (pes_matrix_) with centrifugal matrix \(W_{\mathrm{N}} = V_{\mathrm{N}} + 1/R^{2} L^{2} \)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: intermolecular_distance_
intermolecular distance
real(kind=dp), intent(in) :: pes_matrix_(:,:)
holds contribution from the interaction potential, total and and internal energy
real(kind=dp), intent(in) :: centrifugal_matrix_(:,:)
\(R^{2}\) centrifugal matrix
real(kind=dp), intent(inout) :: coupling_matrix_(:,:)
(output) Coupling (W) matrix
Called by
Contents
Source Code
calculate_coupling_matrix
Source Code
      subroutine calculate_coupling_matrix(intermolecular_distance_,           &
         pes_matrix_, centrifugal_matrix_, coupling_matrix_)
         !! Combines the contribution from the interaction potential, total and
         !! and internal energy (pes_matrix_) with centrifugal matrix
         !! \\( W_{\mathrm{N}} = V_{\mathrm{N}} + 1/R^{2} L^{2} \\)
         !---------------------------------------------------------------------!
         real(dp), intent(in) :: intermolecular_distance_
            !! intermolecular distance
         real(dp), intent(in) :: pes_matrix_(:,:)
            !! holds contribution from the interaction potential, total and
            !! and internal energy
         real(dp), intent(in) :: centrifugal_matrix_(:,:)
            !! \\(R^{2}\\) centrifugal matrix
         real(dp), intent(inout) :: coupling_matrix_(:,:)
            !! (output) Coupling (W) matrix
         !---------------------------------------------------------------------!
         coupling_matrix_ = pes_matrix_                                        &
            + (1.0_dp/intermolecular_distance_**2.0_dp) * centrifugal_matrix_
         !---------------------------------------------------------------------!
      end subroutine calculate_coupling_matrix
Call graph
initial_setup calls calculate_coupling_matrix
general_propagation_step calls calculate_coupling_matrix
numerov calls initial_setup, general_propagation_step, handle_final_propagation_steps
handle_final_propagation_steps calls general_propagation_step
scattering calls numerov