cenitrfugal_matrix – the SCATTERING code
cenitrfugal_matrix Subroutine
37 statements
Source File
public subroutine cenitrfugal_matrix(number_of_channels, jj, channels_level_indices, channels_omega_values, centmatrix)
calculates the (R*2)centrifugal matrix from Eq. (6.19) only called once at the beginning of the calculations
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: number_of_channels
size of the basis
integer(kind=int32), intent(in) :: jj
total angular momentum
integer(kind=int32), intent(in) :: channels_level_indices(number_of_channels)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(in) :: channels_omega_values(number_of_channels)
holds all values of \bar{\Omega}
real(kind=dp), intent(out) :: centmatrix(number_of_channels,number_of_channels)
(output) - (R*2)centrifugal matrix
Calls
Called by
Contents
Variables
centtmp delta1 delta2 ii ij j1ptmp j1tmp omegaptmp omegatmp v1ptmp v1tmp
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: centtmp
real(kind=dp), public :: delta1
real(kind=dp), public :: delta2
integer(kind=int32), public :: ii
integer(kind=int32), public :: ij
integer(kind=int32), public :: j1ptmp
integer(kind=int32), public :: j1tmp
integer(kind=int32), public :: omegaptmp
integer(kind=int32), public :: omegatmp
integer(kind=int32), public :: v1ptmp
integer(kind=int32), public :: v1tmp
Call graph
cenitrfugal_matrix calls dfloat, fill_symmetric_matrix
numerov calls cenitrfugal_matrix
scattering calls numerov