check_namelist_potential – the SCATTERING code
check_namelist_potential Subroutine
22 statements
Source File
public subroutine check_namelist_potential()
Check variables read from namelist "potential"
Arguments
None
Calls
Called by
Contents
Variables
column_index_ legendre_index_
Source Code
check_namelist_potential
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: column_index_
integer(kind=int32), public :: legendre_index_
Source Code
      subroutine check_namelist_potential
         !! Check variables read from namelist "potential"
         !---------------------------------------------------------------------!
         integer(int32) :: legendre_index_, column_index_
         !---------------------------------------------------------------------!
         do legendre_index_ = 1, number_of_legendre_indices
            if (legendre_indices(legendre_index_) < 0) then
               call incorrect_value("legendre_indices(" //                     &
                  integer_to_character(legendre_index_) // ")",                &
                  legendre_indices(legendre_index_), input_unit)
            endif
         enddo
         do column_index_ = 1, total_number_of_coupling_terms
            if (vib_couplings(column_index_) < 0) then
               call incorrect_value("vib_couplings(" //                        &
                  integer_to_character(column_index_) // ")",                  &
                  vib_couplings(column_index_), input_unit)
            endif
            if (rot_couplings(column_index_) < 0) then
               call incorrect_value("rot_couplings(" //                        &
                  integer_to_character(column_index_) // ")",                  &
                  rot_couplings(column_index_), input_unit)
            endif
            if (vib_prime_couplings(column_index_) < 0) then
               call incorrect_value("vp1pes(" //                               &
                  integer_to_character(column_index_) // ")",                  &
                  vib_prime_couplings(column_index_), input_unit)
            endif
            if (rot_prime_couplings(column_index_) < 0) then
               call incorrect_value("rot_prime_couplings(" //                  &
                  integer_to_character(column_index_) // ")",                  &
                  rot_prime_couplings(column_index_), input_unit)
            endif
         enddo
      end subroutine check_namelist_potential
Call graph
check_namelist_potential calls integer_to_character, incorrect_value
incorrect_value calls incorrect_value_ch, incorrect_value_int32, incorrect_value_dp, incorrect_value_sp
incorrect_value_ch calls write_error
incorrect_value_int32 calls write_error
incorrect_value_dp calls write_error
incorrect_value_sp calls write_error
write_error calls write_message
read_input_file calls check_namelist_potential
scattering calls read_input_file