CROSSSECTION – the SCATTERING code
CROSSSECTION Subroutine
81 statements
Source File
public subroutine CROSSSECTION(jj, nopen, number_of_channels, number_of_open_basis_levels, open_basis_levels, open_basis_wavevectors, srmatrix, simatrix, channels_level_indices, channels_l_values, xs_array)
calculate the state-to-state cross-section
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: jj
total angular momentum
integer(kind=int32), intent(in) :: nopen
number of open channels
integer(kind=int32), intent(in) :: number_of_channels
size of the basis
integer(kind=int32), intent(in) :: number_of_open_basis_levels
number of all possible state-to-state XS
integer(kind=int32), intent(in) :: open_basis_levels(number_of_open_basis_levels)
holds indices to the basis arrays which correspond to open channels
real(kind=dp), intent(in) :: open_basis_wavevectors(number_of_open_basis_levels)
holds wavenumbers k_{i}
real(kind=dp), intent(in) :: srmatrix(nopen,nopen)
real and imaginary parts of the S-matrix
real(kind=dp), intent(in) :: simatrix(nopen,nopen)
real and imaginary parts of the S-matrix
integer(kind=int32), intent(in) :: channels_level_indices(number_of_channels)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(in) :: channels_l_values(number_of_channels)
holds all values of l
real(kind=dp), intent(inout) :: xs_array(number_of_open_basis_levels*number_of_open_basis_levels)
array holding all XSs
Calls
Called by
Contents
Variables
ifin ii iinit il ilp ioccur1 ioccur2 j1lev j1plev jblockarr jfin jinit jpblockarr lptmp ltmp njoccur njpoccur teli telr telsq time_finish time_start v1lev v1plev waveinit xs_time xssum
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: ifin
integer(kind=int32), public :: ii
integer(kind=int32), public :: iinit
integer(kind=int32), public :: il
integer(kind=int32), public :: ilp
integer(kind=int32), public :: ioccur1
integer(kind=int32), public :: ioccur2
integer(kind=int32), public :: j1lev
integer(kind=int32), public :: j1plev
integer(kind=int32), public, allocatable :: jblockarr(:)
integer(kind=int32), public :: jfin
integer(kind=int32), public :: jinit
integer(kind=int32), public, allocatable :: jpblockarr(:)
integer(kind=int32), public :: lptmp
integer(kind=int32), public :: ltmp
integer(kind=int32), public :: njoccur
integer(kind=int32), public :: njpoccur
real(kind=dp), public :: teli
real(kind=dp), public :: telr
real(kind=dp), public :: telsq
real(kind=dp), public :: time_finish
real(kind=dp), public :: time_start
integer(kind=int32), public :: v1lev
integer(kind=int32), public :: v1plev
real(kind=dp), public :: waveinit
real(kind=dp), public :: xs_time
real(kind=dp), public :: xssum
Call graph
crosssection calls allocate_1d, time_count_summary
time_count_summary calls write_message
scattering calls crosssection