envj – the SCATTERING code
envj Function
17 statements
Source File
public function envj(n, x)
utility function used by MSTA1 and MSTA2.
Arguments
Type Intent Optional Attributes Name
integer(kind=4) :: n
real(kind=8) :: x
Return Value real(kind=8)
Called by
Contents
Variables
logten n_r8 r8_gamma_log
Variables
Type Visibility Attributes Name Initial
real(kind=8), public :: logten
real(kind=8), public :: n_r8
real(kind=8), public :: r8_gamma_log
Call graph
msta1 calls envj
msta2 calls envj
ikv calls msta1, msta2
rctj calls msta1, msta2
modified_bessel_k_ratio calls ikv
riccati_bessel_j calls rctj
calculate_k_matrix calls modified_bessel_k_ratio, riccati_bessel_j
scattering calls calculate_k_matrix