ETOTAL – the SCATTERING code
ETOTAL Function
8 statements
Source File
public function ETOTAL() result(etot_)
returns the total energy
Arguments
None
Return Value real(kind=dp)
Called by
Contents
None
Call graph
is_open calls etotal
scattering calls etotal, calculate_k_matrix, save_open_basis_levels, read_input_file, count_open_basis_levels, calculate_largest_wavenumber, count_open_channels_in_block, print_channels, numerov
input_summary calls etotal
wavenumber_squared_from_energy calls etotal
calculate_k_matrix calls is_open, wavenumber_squared_from_energy
save_open_basis_levels calls is_open, wavenumber_squared_from_energy
read_input_file calls input_summary
calculate_single_pes_matrix_element calls wavenumber_squared_from_energy
count_open_basis_levels calls is_open
calculate_largest_wavenumber calls is_open, wavenumber_squared_from_energy
count_open_channels_in_block calls is_open
print_channels calls is_open, wavenumber_squared_from_energy
pes_contribution calls calculate_single_pes_matrix_element
numerov calls pes_contribution