float_to_character – the SCATTERING code
float_to_character Function
14 statements
Source File
public function float_to_character(f, format_string) result(res)
Converts a floating-point number to a character string.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: f
input floating-point number
character(len=*), intent(in), optional :: format_string
Optional format string.
Return Value character(len=64)
Output character string.
Called by
Contents
Variables
default_format user_format
Source Code
float_to_character
Variables
Type Visibility Attributes Name Initial
character(len=32), private :: default_format
character(len=32), private :: user_format
Source Code
      function float_to_character(f, format_string) result(res)
         !! Converts a floating-point number to a character string.
         !---------------------------------------------------------------------!
         real(dp), intent(in) :: f
            !! input floating-point number
         character(len=*), intent(in), optional :: format_string
            !! Optional format string.
         character(len=64) :: res
            !! Output character string.
         !---------------------------------------------------------------------!
         character(len=32) :: default_format, user_format
         !---------------------------------------------------------------------!
         ! Default format: 6 decimal places
         !---------------------------------------------------------------------!
         default_format = '(F0.6)'
         !---------------------------------------------------------------------!
         if (present(format_string)) then
            user_format = trim(format_string)
         else
            user_format = default_format
         endif
         !---------------------------------------------------------------------!
         write(res, user_format) f
         res = adjustl(res)
         !---------------------------------------------------------------------!
      end function float_to_character
Call graph
ispline calls float_to_character
validate_r_range calls float_to_character
print_cross_sections_for_jtot calls float_to_character
input_summary calls float_to_character
print_sum_of_squares calls float_to_character
propagator_summary calls float_to_character
print_basic_cross_section_info calls float_to_character
read_input_file calls input_summary
get_radial_coupling_term_value calls ispline
scattering calls print_cross_sections_for_jtot, read_input_file, read_radial_coupling_terms, numerov, print_largest_partial_cross_sections, unitarity_check
read_radial_coupling_terms calls validate_r_range
handle_unitarity_output_message calls print_sum_of_squares
numerov calls propagator_summary
print_largest_partial_cross_sections calls print_basic_cross_section_info
calculate_single_pes_matrix_element calls get_radial_coupling_term_value
unitarity_check calls handle_unitarity_output_message
calculate_pes_matrix calls calculate_single_pes_matrix_element
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix