incorrect_value_int32 – the SCATTERING code
incorrect_value_int32 Subroutine
10 statements
Source File
private subroutine incorrect_value_int32(name_, value_, unit_)
incorrect value encountered: variable_name = variable_value
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_
name of the variable
integer(kind=int32), intent(in) :: value_
value of the variable
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
Calls
Called by
Contents
Variables
add_prefix_ tmp_
Source Code
incorrect_value_int32
Variables
Type Visibility Attributes Name Initial
character(len=:), private, allocatable :: add_prefix_
character(len=20), private :: tmp_
Source Code
      subroutine incorrect_value_int32(name_, value_, unit_)
         !! ``incorrect value encountered:
         !!   variable_name = variable_value``
         !---------------------------------------------------------------------!
         character(len = *), intent(in)       :: name_
            !! name of the variable
         integer(int32), intent(in)           :: value_
            !! value of the variable
         integer(int32), optional, intent(in) :: unit_
            !! optional, unit where the message will be written
         !---------------------------------------------------------------------!
         character(len = 20)              :: tmp_
         character(len = :),  allocatable :: add_prefix_
         !---------------------------------------------------------------------!
         write(tmp_, '(i5)') value_
         add_prefix_ = 'Incorrect value encountered:  '//trim(name_)//' = '//  &
                       trim(tmp_)
         call write_error(add_prefix_, unit_)
         !---------------------------------------------------------------------!
      end subroutine incorrect_value_int32
Call graph
incorrect_value_int32 calls write_error
write_error calls write_message
incorrect_value calls incorrect_value_int32
check_namelist_input calls incorrect_value
write_header calls incorrect_value
check_namelist_basis calls incorrect_value
check_namelist_potential calls incorrect_value
read_input_file calls check_namelist_input, check_namelist_basis, check_namelist_potential
scattering calls write_header, read_input_file