initialize_pes_matrix – the SCATTERING code
initialize_pes_matrix Subroutine
21 statements
Source File
public subroutine initialize_pes_matrix(channel_indices, channels_omega_values, nonzero_terms_per_element, nonzero_legendre_indices, nonzero_algebraic_coefficients)
launches "check_nonzero_pes_matrix_elements" and "prepare_pes_matrix_elements" subroutines; called from the main program
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: channel_indices(:)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(in) :: channels_omega_values(:)
holds all values of \bar{\Omega}
integer(kind=int32), intent(inout), allocatable :: nonzero_terms_per_element(:)
keeps the number of non-vanishing elements of the sum over \(\lambda\) for each non-zero element of the PES matrix
integer(kind=int32), intent(inout), allocatable :: nonzero_legendre_indices(:)
holds indices pointing to legendre_indices, which correspond to the non-vanishing elements of the sum over \(\lambda\) for each non-zero element of the PES matrix;
real(kind=dp), intent(inout), allocatable :: nonzero_algebraic_coefficients(:)
holds the values of the non-zero algebraic coefficients
Calls
Called by
Contents
Variables
number_of_channels number_of_nonzero_algebraic_coefficients number_of_nonzero_pes_matrix_elements time_start_ time_stop_ total_time_
Source Code
initialize_pes_matrix
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: number_of_channels
integer(kind=int32), private :: number_of_nonzero_algebraic_coefficients
integer(kind=int32), private :: number_of_nonzero_pes_matrix_elements
real(kind=dp), private :: time_start_
real(kind=dp), private :: time_stop_
real(kind=dp), private :: total_time_
Source Code
      subroutine initialize_pes_matrix(channel_indices,                        &
         channels_omega_values, nonzero_terms_per_element,                     &
         nonzero_legendre_indices, nonzero_algebraic_coefficients)
         !! launches "check_nonzero_pes_matrix_elements" and
         !! "prepare_pes_matrix_elements" subroutines; called from
         !! the main program
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: channel_indices(:)
            !! holds the indices pointing to the basis arrays
         integer(int32), intent(in) :: channels_omega_values(:)
            !! holds all values of \bar{\Omega}
         integer(int32), intent(inout), allocatable :: nonzero_terms_per_element(:)
            !! keeps the number of non-vanishing elements of the sum over \\(\lambda\\)
            !! for each non-zero element of the PES matrix
         integer(int32), intent(inout), allocatable :: nonzero_legendre_indices(:)
            !! holds indices pointing to legendre_indices, which correspond to
            !! the non-vanishing elements of the sum over \\(\lambda\\)
            !! for each non-zero element of the PES matrix;
         real(dp), intent(inout), allocatable :: nonzero_algebraic_coefficients(:)
            !! holds the values of the non-zero algebraic coefficients
         !---------------------------------------------------------------------!
         integer(int32) :: number_of_channels,                                 &
            number_of_nonzero_pes_matrix_elements,                             &
            number_of_nonzero_algebraic_coefficients
         real(dp) :: time_start_, time_stop_, total_time_
         !---------------------------------------------------------------------!
         call cpu_time(time_start_)
         !---------------------------------------------------------------------!
         call check_nonzero_pes_matrix_elements(channel_indices,               &
            channels_omega_values, number_of_nonzero_pes_matrix_elements,      &
            number_of_nonzero_algebraic_coefficients)
         !---------------------------------------------------------------------!
         call allocate_1d(nonzero_terms_per_element,number_of_nonzero_pes_matrix_elements)
         call allocate_1d(nonzero_algebraic_coefficients,number_of_nonzero_algebraic_coefficients)
         call allocate_1d(nonzero_legendre_indices,number_of_nonzero_algebraic_coefficients)
         !---------------------------------------------------------------------!
         call prepare_pes_matrix_elements(channel_indices,                     &
            channels_omega_values, nonzero_terms_per_element,                  &
            nonzero_legendre_indices, nonzero_algebraic_coefficients)
         !---------------------------------------------------------------------!
         call cpu_time(time_stop_)
         !---------------------------------------------------------------------!
         if (print_level.ge.2) then
            !------------------------------------------------------------------!
            number_of_channels = size(channel_indices)
            call print_pes_matrix_elements_summary(                            &
               number_of_channels, number_of_nonzero_pes_matrix_elements,      &
               number_of_nonzero_algebraic_coefficients)
            !------------------------------------------------------------------!
            call time_count_summary(time_start_, time_stop_, total_time_,      &
               "-- PES matrix initialization completed in ")
            !------------------------------------------------------------------!
         endif
         !---------------------------------------------------------------------!
      end subroutine initialize_pes_matrix
Call graph
initialize_pes_matrix calls check_nonzero_pes_matrix_elements, prepare_pes_matrix_elements, print_pes_matrix_elements_summary, time_count_summary, allocate_1d
check_nonzero_pes_matrix_elements calls zero_projections_3j_condition
prepare_pes_matrix_elements calls process_single_matrix_element
print_pes_matrix_elements_summary calls write_message, integer_to_character
time_count_summary calls write_message
zero_projections_3j_condition calls triangle_inequality_holds, is_sum_even
process_single_matrix_element calls zero_projections_3j_condition, percival_seaton_coefficient
percival_seaton_coefficient calls fwig3jj
scattering calls initialize_pes_matrix