initial_setup – the SCATTERING code
initial_setup Subroutine
20 statements
Source File
private subroutine initial_setup(number_of_channels_, step_numerov_, total_angular_momentum_, intermolecular_distance_, channel_indices_, channels_omega_values_, nonzero_terms_per_element_, nonzero_legendre_indices_, nonzero_algebraic_coefficients_, centrifugal_matrix_, r_matrix_)
Initial setup of the propagator: call centrifugal matrix (kept throughotu the propagation) and other matrices at \(R_{\mathrm{min}}\)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: number_of_channels_
size of the basis
real(kind=dp), intent(in) :: step_numerov_
step of the propagator
integer(kind=int32), intent(in) :: total_angular_momentum_
total angular momentum
real(kind=dp), intent(in) :: intermolecular_distance_
intermolecular distance
integer(kind=int32), intent(in) :: channel_indices_(number_of_channels_)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(in) :: channels_omega_values_(number_of_channels_)
holds all values of \bar{\Omega}
integer(kind=int32), intent(in) :: nonzero_terms_per_element_(:)
keeps the number of non-vanishing elements of the sum over \(\lambda\) for each non-zero element of the pes matrix
integer(kind=int32), intent(in) :: nonzero_legendre_indices_(:)
holds indices pointing to legendre_indices, which correspond to the non-vanishing elements of the sum over \(\lambda\) for each non-zero element of the pes matrix;
real(kind=dp), intent(in) :: nonzero_algebraic_coefficients_(:)
holds the values of the non-zero algebraic coefficients
real(kind=dp), intent(inout) :: centrifugal_matrix_(number_of_channels_,number_of_channels_)
(R*2)centrifugal matrix - calculated once, will be used throughout the propagation
real(kind=dp), intent(inout) :: r_matrix_(number_of_channels_,number_of_channels_)
R-matrix at r_min
Calls
Called by
Contents
Variables
coupling_matrix_ pes_matrix_ t_matrix_ u_matrix_
Source Code
initial_setup
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private, dimension(number_of_channels_,number_of_channels_) :: coupling_matrix_
real(kind=dp), private, dimension(number_of_channels_,number_of_channels_) :: pes_matrix_
real(kind=dp), private, dimension(number_of_channels_,number_of_channels_) :: t_matrix_
real(kind=dp), private, dimension(number_of_channels_,number_of_channels_) :: u_matrix_
Source Code
      subroutine initial_setup(number_of_channels_, step_numerov_,             &
         total_angular_momentum_, intermolecular_distance_, channel_indices_,  &
         channels_omega_values_, nonzero_terms_per_element_,                   &
         nonzero_legendre_indices_, nonzero_algebraic_coefficients_,           &
         centrifugal_matrix_, r_matrix_)
         !! Initial setup of the propagator: call centrifugal matrix
         !! (kept throughotu the propagation) and other matrices
         !! at \\(R_{\mathrm{min}}\\)
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: number_of_channels_
            !! size of the basis
         real(dp), intent(in) :: step_numerov_
            !! step of the propagator
         integer(int32), intent(in) :: total_angular_momentum_
            !! total angular momentum
         real(dp), intent(in) :: intermolecular_distance_
            !! intermolecular distance
         integer(int32), intent(in) :: channel_indices_(number_of_channels_)
            !! holds the indices pointing to the basis arrays
         integer(int32), intent(in) :: channels_omega_values_(number_of_channels_)
            !! holds all values of \bar{\Omega}
         integer(int32), intent(in) :: nonzero_terms_per_element_(:)
            !! keeps the number of non-vanishing elements of the
            !! sum over \\(\lambda\\) for each non-zero element of the pes matrix
         integer(int32), intent(in) :: nonzero_legendre_indices_(:)
            !! holds indices pointing to legendre_indices, which correspond to
            !! the non-vanishing elements of the sum over \\(\lambda\\)
            !! for each non-zero element of the pes matrix;
         real(dp), intent(in) :: nonzero_algebraic_coefficients_(:)
            !! holds the values of the non-zero algebraic coefficients
         real(dp), intent(inout) :: centrifugal_matrix_(number_of_channels_,number_of_channels_)
            !! (R**2)*centrifugal matrix - calculated once,
            !! will be used throughout the propagation
         real(dp), intent(inout) :: r_matrix_(number_of_channels_,number_of_channels_)
            !! R-matrix at r_min
         !---------------------------------------------------------------------!
         real(dp), dimension(number_of_channels_,number_of_channels_) ::       &
            pes_matrix_, coupling_matrix_, t_matrix_, u_matrix_
         !---------------------------------------------------------------------!
         ! Calculate centrifugal matrix
         !---------------------------------------------------------------------!
         call calculate_centrifugal_matrix(total_angular_momentum_,            &
            channel_indices_, channels_omega_values_, centrifugal_matrix_)
         !---------------------------------------------------------------------!
         ! Calculate PES matrix at r_min
         !---------------------------------------------------------------------!
         call calculate_pes_matrix(total_angular_momentum_,                    &
            intermolecular_distance_, channel_indices_,                        &
            channels_omega_values_, nonzero_terms_per_element_,                &
            nonzero_legendre_indices_, nonzero_algebraic_coefficients_, pes_matrix_)
         !---------------------------------------------------------------------!
         ! Merge centrifugal and PES matrix into Coupling matrix
         !---------------------------------------------------------------------!
         call calculate_coupling_matrix(intermolecular_distance_, pes_matrix_, &
            centrifugal_matrix_, coupling_matrix_)
         !---------------------------------------------------------------------!
         ! Calculate initial T-matrix and U-matrix
         !---------------------------------------------------------------------!
         call calculate_t_matrix(step_numerov_, coupling_matrix_, t_matrix_)
         call calculate_u_matrix(t_matrix_, u_matrix_)
         !---------------------------------------------------------------------!
         ! Initialize R-matrix: R-matrix at r_min + 1 = U-matrix at r_min
         !---------------------------------------------------------------------!
         r_matrix_ = u_matrix_
         !---------------------------------------------------------------------!
      end subroutine initial_setup
Call graph
initial_setup calls calculate_pes_matrix, calculate_u_matrix, calculate_centrifugal_matrix, calculate_coupling_matrix, calculate_t_matrix
calculate_pes_matrix calls calculate_single_pes_matrix_element, fill_symmetric_matrix
calculate_u_matrix calls invert_symmetric_matrix, fill_symmetric_matrix, add_scalar_to_diagonal
calculate_centrifugal_matrix calls fill_symmetric_matrix, delta_for_zero_omega, calculate_diagonal_centrifugal_element, calculate_offdiagonal_centrifugal_element
calculate_single_pes_matrix_element calls get_radial_coupling_term_value, wavevector_squared_from_energy
get_radial_coupling_term_value calls find_lambda_index, find_coupling_index, ispline, handle_lambda_index_error, handle_coupling_index_error
wavevector_squared_from_energy calls total_energy, write_error
ispline calls float_to_character, write_warning
handle_lambda_index_error calls write_error, integer_to_character
handle_coupling_index_error calls write_error, integer_to_character
write_error calls write_message
numerov calls initial_setup
scattering calls numerov