input_summary – the SCATTERING code
input_summary Subroutine
28 statements
Source File
public subroutine input_summary()
summarize the input parameters for the current run
Arguments
None
Calls
Called by
Contents
Variables
ilevel
Source Code
input_summary
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: ilevel
Source Code
   subroutine input_summary
      !! summarize the input parameters for the current run
      !------------------------------------------------------------------------!
      integer(int32) :: ilevel
      !------------------------------------------------------------------------!
      call write_message("User-supplied label: " // label)
      call write_message("Reduced mass: " //                                   &
         trim(adjustl(float_to_character(reducedmass, "(F10.4)"))) // " a.m.u.")
      call write_message("*** Energy levels in the basis set: ***")
      call write_message("   v       j            Energy (cm^{-1})")
      do ilevel = 1,nlevel
         write(*,"(I4,4X,I4,16X,F12.4)") v1array(ilevel), j1array(ilevel), elevel(ilevel)
      enddo
      write(*,"(44X,A3)") "***"
      if (jtotmax.ne.999999) then
         call write_message("The equations will be solved" //                  &
            "for total angular momentum J from " //                            &
            trim(adjustl(integer_to_character(jtotmin))) // " to "             &
            // trim(adjustl(integer_to_character(jtotmax))) // "with step" //  &
            trim(adjustl(integer_to_character(jtotstep))))
      else
         call write_message("The loop over JTOT will be performed from " //    &
            trim(adjustl(integer_to_character(jtotmin))) // " with step " //   &
            trim(adjustl(integer_to_character(jtotstep))) // " until " //      &
            trim(adjustl(integer_to_character(ncac))) //                       &
            " consecutive JTOT-blocks contribute less than " //                &
            trim(adjustl(float_to_character(dtol, "(E10.4)"))) //              &
            " A^2 to the elastic XS and less than " //                         &
            trim(adjustl(float_to_character(otol, "(E10.4)"))) //              &
            " A^2 to the inelastic XS")
      endif
      if (ietoterel.eq.0) then
         call write_message("The calculations will be performed for the total energy equal to "&
            // trim(adjustl(float_to_character(ETOTAL(), "(F10.4)")))//" cm-1")
      else if(ietoterel.eq.1) then
         call write_message("Relative kinetic energy of the colliding system: " //&
            trim(adjustl(float_to_character(energy, "(F10.4)"))) // " cm-1")
         call write_message("and the corresponding wavenumber: " // &
            trim(adjustl(float_to_character(WAVENUMBEREKIN(), "(F10.4)"))) //  &
            " 1/Ang")
         call write_message("The kinetic energy is calculated with respect to the" //&
            " v = " // trim(adjustl(integer_to_character(v1array(initial)))) //&
            " j = " // trim(adjustl(integer_to_character(j1array(initial)))) //&
            " level in the basis set with the rotational energy " //           &
            trim(adjustl(float_to_character(elevel(initial), "(F10.4)")))      &
            // " cm-1.")
         call write_message("This gives the total energy equal to " // &
            trim(adjustl(float_to_character(ETOTAL(), "(F10.4)"))) // " cm-1")
      endif
      if (ipart.eq.1) then
         call write_message("Partial cross sections will be saved into " // partialfile )
      endif
      call write_message("S-matrix elements will be saved into " // smatrixfile )
      !------------------------------------------------------------------------!
   end subroutine input_summary
Call graph
input_summary calls write_message, float_to_character, etotal, integer_to_character, wavenumberekin
wavenumberekin calls etotal, write_error
write_error calls write_message
read_input_file calls input_summary
scattering calls read_input_file