input_check – the SCATTERING code
input_check Subroutine
123 statements
Source File
public subroutine input_check(nmlistind)
checks if the supplied input parameters are correct
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nmlistind
nmlistind = 1: namelist INPUT nmlistind = 2: namelist BASIS nmlistind = 3: namelist POTENTIAL
Calls
Called by
Contents
Variables
icol il ilevel
Source Code
input_check
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: icol
integer(kind=int32), public :: il
integer(kind=int32), public :: ilevel
Source Code
   subroutine input_check(nmlistind)
      !! checks if the supplied input parameters are correct
      !------------------------------------------------------------------------!
      integer(int32), intent(in) :: nmlistind
         !! nmlistind = 1: namelist INPUT
         !! nmlistind = 2: namelist BASIS
         !! nmlistind = 3: namelist POTENTIAL
      !------------------------------------------------------------------------!
      integer(int32) :: ilevel, il, icol
      !------------------------------------------------------------------------!
      if (nmlistind.eq.1) then
      !------------------------------------------------------------------------!
      ! Namelist input:
      !------------------------------------------------------------------------!
         if (reducedmass.lt.0) then
            call incorrect_value("reducedmass", reducedmass, 5)
         endif
         if ((ietoterel.ne.0).and.(ietoterel.ne.1)) then
            call incorrect_value("ietoterel", ietoterel, 5)
         endif
         if (energy.lt.0) then
            call incorrect_value("energy", energy, 5)
         endif
         if (rmin.le.0) then
            call incorrect_value("rmin", rmin, 5)
         endif
         if (rmax.le.0) then
            call incorrect_value("rmax", rmax, 5)
         endif
         if (rmax.lt.rmin) then
            call incorrect_value("rmax/rmin", rmax / rmin, 5)
         endif
         if (steps.le.0.d0) then
            call incorrect_value("steps", steps, 5)
         endif
         if (vdepth.lt.0.d0) then
            call incorrect_value("vdepth", vdepth, 5)
         endif
         if (jtotmin.lt.0) then
            call incorrect_value("jtotmin", jtotmin, 5)
         endif
         if (jtotmax.lt.0) then
            if (ncac.lt.0) then
               call write_message("JTOTMAX < 0:")
               call incorrect_value("ncac", ncac, 5)
            endif
            if (dtol.lt.0) then
               call write_message("JTOTMAX < 0:")
               call incorrect_value("dtol", dtol, 5)
            endif
            if (otol.lt.0) then
               call write_message("JTOTMAX < 0:")
               call incorrect_value("otol", otol, 5)
            endif
            else
                if (jtotmax.lt.jtotmin) then
               call write_message("jtotmax is smaller than jtotmin")
               call incorrect_value("jtotmax/jtotmin",                         &
                  real(jtotmax/jtotmin, dp), 5)
            endif
         endif
         if (nlevel.le.0) then
            call incorrect_value("nlevel", nlevel, 5)
         endif
         if (ietoterel.eq.1) then
            if (initial.le.0) then
               call write_message("ietoterel = 1:")
               call incorrect_value("initial", initial, 5)
            endif
            if (initial.gt.nlevel) then
               call write_message("ietoterel = 1:")
               call write_message("nlevel = " // integer_to_character(nlevel))
               call incorrect_value("initial > nlevel", initial, 5)
            endif
         endif
         if (nr.le.0) then
            call incorrect_value("nr", nr, 5)
         endif
         if (nterms.le.0) then
            call incorrect_value("nterms", nterms, 5)
         endif
         if (totalcol.le.0) then
            call incorrect_value("totalcol", totalcol, 5)
         endif
         if (n_skip_lines.lt.0) then
            call incorrect_value("n_skip_lines", n_skip_lines, 5)
         endif
         if ((iunits.ne.0).and.(iunits.ne.1)) then
            call incorrect_value("iunits", iunits, 5)
         endif
         inquire(file = potentialfile, exist = pes_file_exists)
         if (pes_file_exists.eqv..false.) then
            call write_error(trim(adjustl(potentialfile)) // " does not exist")
         endif
         if ((ipart.ne.0).and.(ipart.ne.1)) then
            call incorrect_value("ipart", ipart, 5)
         endif
         if (prntlvl.lt.0) then
            call incorrect_value("prntlvl", prntlvl, 5)
         endif
      !------------------------------------------------------------------------!
      else if (nmlistind.eq.2) then
      !------------------------------------------------------------------------!
      ! Namelist basis:
      !------------------------------------------------------------------------!
         do ilevel = 1, nlevel
            if (v1array(ilevel).lt.0) then
               call incorrect_value("v1array(" // integer_to_character(ilevel) // ")", v1array(ilevel), 5)
            endif
            if (j1array(ilevel).lt.0) then
               call incorrect_value("j1array(" // integer_to_character(ilevel) // ")", j1array(ilevel), 5)
            endif
            if (elevel(ilevel).lt.0.0_dp) then
               call incorrect_value("elevel(" // integer_to_character(ilevel) // ")", elevel(ilevel), 5)
            endif
         enddo
      !------------------------------------------------------------------------!
      else if (nmlistind.eq.3) then
      !------------------------------------------------------------------------!
      ! Namelist potential:
      !------------------------------------------------------------------------!
         do il = 1, nterms
            if (l1tab(il).lt.0) then
               call incorrect_value("l1tab(" // integer_to_character(il) // ")", l1tab(il), 5)
            endif
         enddo
         do icol = 1, totalcol
            if (v1pes(icol).lt.0) then
               call incorrect_value("v1pes(" // integer_to_character(icol) // ")", v1pes(icol), 5)
            endif
            if (j1pes(icol).lt.0) then
               call incorrect_value("j1pes(" // integer_to_character(icol) // ")", j1pes(icol), 5)
            endif
            if (v1ppes(icol).lt.0) then
               call incorrect_value("vp1pes(" // integer_to_character(icol) // ")", v1ppes(icol), 5)
            endif
            if (j1ppes(icol).lt.0) then
               call incorrect_value("j1ppes(" // integer_to_character(icol) // ")", j1ppes(icol), 5)
            endif
         enddo
      endif
      !------------------------------------------------------------------------!
   end subroutine input_check
Call graph
input_check calls incorrect_value, write_message, write_error, integer_to_character
write_error calls write_message
read_input_file calls input_check
scattering calls read_input_file