integer_to_character – the SCATTERING code
integer_to_character Function
14 statements
Source File
public function integer_to_character(i, format_string) result(res)
transfers integer to a character
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: i
input integer
character(len=*), intent(in), optional :: format_string
Optional format string.
Return Value character(len=32)
output character
Called by
Contents
Variables
default_format user_format
Source Code
integer_to_character
Variables
Type Visibility Attributes Name Initial
character(len=32), private :: default_format
character(len=32), private :: user_format
Source Code
      function integer_to_character(i, format_string) result(res)
         !! transfers integer to a character
         !---------------------------------------------------------------------!
         integer, intent(in) :: i
            !! input integer
         character(len=*), intent(in), optional :: format_string
            !! Optional format string.
         character(len=32) :: res
            !! output character
         !---------------------------------------------------------------------!
         character(len=32) :: default_format, user_format
         !---------------------------------------------------------------------!
         ! Deafult format
         !---------------------------------------------------------------------!
         default_format =  '(i0)'
         !---------------------------------------------------------------------!
         if (present(format_string)) then
            user_format = trim(format_string)
         else
            user_format = default_format
         endif
         !---------------------------------------------------------------------!
         write (res, user_format) i
         res = adjustl(res)
         !---------------------------------------------------------------------!
      end function integer_to_character
Call graph
print_pes_matrix_elements_summary calls integer_to_character
print_basic_cross_section_info calls integer_to_character
invert_symmetric_matrix_sp calls integer_to_character
print_pes_quantum_numbers calls integer_to_character
read_and_validate_lambda calls integer_to_character
check_namelist_input calls integer_to_character
check_namelist_basis calls integer_to_character
riccati_bessel_j calls integer_to_character
check_number_of_channels calls integer_to_character
print_cross_sections_for_jtot calls integer_to_character
fill_symmetric_matrix_int32 calls integer_to_character
fill_symmetric_matrix_sp calls integer_to_character
file_io_status calls integer_to_character
print_sum_of_squares calls integer_to_character
propagator_summary calls integer_to_character
input_summary calls integer_to_character
no_open_channels_message calls integer_to_character
print_detailed_cross_section_info calls integer_to_character
print_final_unitarity_warning calls integer_to_character
handle_lambda_index_error calls integer_to_character
spline calls integer_to_character
check_namelist_potential calls integer_to_character
print_short_block_summary calls integer_to_character
fill_symmetric_matrix_dp calls integer_to_character
reduce_radial_coupling_terms calls integer_to_character, print_pes_quantum_numbers
handle_coupling_index_error calls integer_to_character
riccati_bessel_y calls integer_to_character
invert_symmetric_matrix_dp calls integer_to_character
set_number_of_channels calls check_number_of_channels
save_partial_xs_file_header calls file_io_status
numerov calls propagator_summary
interpolate_radial_coupling_terms calls spline
initialize_pes_matrix calls print_pes_matrix_elements_summary
read_input_file calls check_namelist_input, check_namelist_basis, file_io_status, input_summary, check_namelist_potential
print_largest_partial_cross_sections calls print_basic_cross_section_info, print_detailed_cross_section_info
calculate_k_matrix calls riccati_bessel_j, riccati_bessel_y
read_radial_coupling_terms calls read_and_validate_lambda, file_io_status
scattering calls print_cross_sections_for_jtot, no_open_channels_message, print_final_unitarity_warning, print_short_block_summary, reduce_radial_coupling_terms, set_number_of_channels, save_partial_xs_file_header, numerov, interpolate_radial_coupling_terms, initialize_pes_matrix, read_input_file, print_largest_partial_cross_sections, calculate_k_matrix, read_radial_coupling_terms, save_s_matrix_file_header, unitarity_check
save_s_matrix_file_header calls file_io_status
handle_unitarity_output_message calls print_sum_of_squares
get_radial_coupling_term_value calls handle_lambda_index_error, handle_coupling_index_error
unitarity_check calls handle_unitarity_output_message
calculate_single_pes_matrix_element calls get_radial_coupling_term_value
calculate_pes_matrix calls calculate_single_pes_matrix_element
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix