is_open – the SCATTERING code
is_open Function
5 statements
Source File
public function is_open(energy_) result(is_open_)
checks if a channel/level is energetically accessible (open) by comparing energy with total_energy
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: energy_
level/channel energy
Return Value logical
Calls
Called by
Contents
Source Code
is_open
Source Code
      function is_open(energy_) result(is_open_)
         !! checks if a channel/level is energetically accessible (open)
         !! by comparing energy with total_energy
         !---------------------------------------------------------------------!
         real(dp), intent(in) :: energy_
            !! level/channel energy
         logical :: is_open_
         !---------------------------------------------------------------------!
         is_open_ = ( energy_ <= total_energy() )
         !---------------------------------------------------------------------!
      end function is_open
Call graph
is_open calls total_energy
calculate_k_matrix calls is_open
count_open_basis_levels calls is_open
save_open_basis_levels calls is_open
count_open_channels_in_block calls is_open
calculate_largest_wavevector calls is_open
prepare_wavevector_array calls is_open
print_channels calls is_open
scattering calls calculate_k_matrix, count_open_basis_levels, save_open_basis_levels, count_open_channels_in_block, calculate_largest_wavevector, prepare_wavevector_array, print_channels