modified_bessel_k_ratio – the SCATTERING code
modified_bessel_k_ratio Subroutine
17 statements
Source File
public subroutine modified_bessel_k_ratio(l_, x_, ratio_)
calculates the ratio of the modified Bessel function of the second kind K_{l_ + 1/2}(x) and its first derivative (Eq. ...) Uses ikv function from special_functions.f90
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: l_
l - order of the function (without the 1/2 factor!)
real(kind=dp), intent(in) :: x_
x - argument of the function
real(kind=dp), intent(inout) :: ratio_
ratio of the modified Bessel function of the second kind to its derivative
Calls
Called by
Contents
Variables
bi_arr_ bk_arr_ di_arr_ dk_arr_ highest_order_ highest_order_real_ order_
Source Code
modified_bessel_k_ratio
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, dimension(l_+1) :: bi_arr_
real(kind=dp), public, dimension(l_+1) :: bk_arr_
real(kind=dp), public, dimension(l_+1) :: di_arr_
real(kind=dp), public, dimension(l_+1) :: dk_arr_
integer(kind=int32), public :: highest_order_
real(kind=dp), public :: highest_order_real_
real(kind=dp), public :: order_
Source Code
   subroutine modified_bessel_k_ratio(l_, x_, ratio_)
      !! calculates the ratio of the modified Bessel function of the second
      !! kind K_{l_ + 1/2}(x) and its first derivative (Eq. ...)
      !! Uses ikv function from special_functions.f90
      !------------------------------------------------------------------------!
      integer(int32), intent(in) :: l_
         !! l - order of the function (without the 1/2 factor!)
      real(dp), intent(in) :: x_
         !! x - argument of the function
      real(dp), intent(inout) :: ratio_
         !! ratio of the modified Bessel function of the second kind to its derivative
      !------------------------------------------------------------------------!
      integer(int32) :: highest_order_
      real(dp) :: order_, highest_order_real_
      real(dp), dimension(l_+1) :: bi_arr_, di_arr_, bk_arr_, dk_arr_
        !------------------------------------------------------------------------!
      order_ = real(l_, dp) + 0.5_dp
      call ikv(order_, x_, highest_order_real_, bi_arr_, di_arr_, bk_arr_, dk_arr_)
      highest_order_ = nint(highest_order_real_ - 0.5_dp)
      !------------------------------------------------------------------------!
      if (highest_order_ < l_) then
         !---------------------------------------------------------------------!
         call write_warning("modified_bessel_k_ratio: maximum order of modified Bessel function:"&
         // trim(adjustl(integer_to_character(highest_order_))) // "is smaller than " //  &
         "requested order l = " // trim(adjustl(integer_to_character(l_))) )
         !---------------------------------------------------------------------!
         ratio_ = dk_arr_(highest_order_) / bk_arr_(highest_order_)
      else
         ratio_ = dk_arr_(l_ + 1) / bk_arr_(l_ + 1)
      endif
      !------------------------------------------------------------------------!
   end subroutine modified_bessel_k_ratio
Call graph
modified_bessel_k_ratio calls ikv, integer_to_character, write_warning
ikv calls msta1, msta2
write_warning calls write_message
msta1 calls envj
msta2 calls envj
calculate_k_matrix calls modified_bessel_k_ratio
scattering calls calculate_k_matrix