numerov – the SCATTERING code
numerov Subroutine
121 statements
Source File
public subroutine numerov(channels_level_indices, channels_omega_values, number_of_nonzero_coupling_matrix_elements, number_of_nonzero_coupling_coefficients, nonzero_terms_per_element, nonzero_legendre_indices, nonzero_coupling_coefficients, nsteps, number_of_channels, jj, log_der_matrix)
renormalized Numerov propagator
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: channels_level_indices(number_of_channels)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(in) :: channels_omega_values(number_of_channels)
holds all values of \bar{\Omega}
integer(kind=int32), intent(in) :: number_of_nonzero_coupling_matrix_elements
number of non-zero terms in the sum () for each non-zero element of the coupling matrix
integer(kind=int32), intent(in) :: number_of_nonzero_coupling_coefficients
number of all non-zero algberaix coefficients in the whole coupling matrix
integer(kind=int32), intent(in) :: nonzero_terms_per_element(number_of_nonzero_coupling_matrix_elements)
keeps the number of non-zero terms in the sum (Eq. (6.21)) for each non-zero element of W/V
integer(kind=int32), intent(in) :: nonzero_legendre_indices(number_of_nonzero_coupling_coefficients)
holds the proper indices pointing to l1/l2/lltabs, which correspond to the non-vanishing elements of the sum (Eq. (6.21)) for each non-zero element of W/V
real(kind=dp), intent(in) :: nonzero_coupling_coefficients(number_of_nonzero_coupling_coefficients)
holds the values of the non-zero algebraic coefficients
integer(kind=int32), intent(in) :: nsteps
number of steps from rmin to rmax
integer(kind=int32), intent(in) :: number_of_channels
size of the basis
integer(kind=int32), intent(in) :: jj
total angular momentum
real(kind=dp), intent(inout) :: log_der_matrix(:,:)
resulting log-derivative matrix at RMAX
Calls
Called by
Contents
Variables
cent_mat finish i ii ij r r_center r_plus r_temp rmatrix start step_numerov t_center t_mat t_minus t_plus u_left u_right umatrix v_mat v_tmp w_mat w_tmp
Source Code
numerov
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public, dimension(number_of_channels,number_of_channels) :: cent_mat
real(kind=dp), public :: finish
integer(kind=int32), public :: i
integer(kind=int32), public :: ii
integer(kind=int32), public :: ij
real(kind=dp), public :: r
real(kind=dp), public, allocatable, dimension(:,:) :: r_center
real(kind=dp), public, allocatable, dimension(:,:) :: r_plus
real(kind=dp), public, allocatable, dimension(:,:) :: r_temp
real(kind=dp), public, allocatable, dimension(:,:) :: rmatrix
real(kind=dp), public :: start
real(kind=dp), public :: step_numerov
real(kind=dp), public, allocatable, dimension(:,:) :: t_center
real(kind=dp), public, dimension(number_of_channels,number_of_channels) :: t_mat
real(kind=dp), public, allocatable, dimension(:,:) :: t_minus
real(kind=dp), public, allocatable, dimension(:,:) :: t_plus
real(kind=dp), public, dimension(number_of_channels,number_of_channels) :: u_left
real(kind=dp), public, dimension(number_of_channels,number_of_channels) :: u_right
real(kind=dp), public, allocatable, dimension(:,:) :: umatrix
real(kind=dp), public, dimension(number_of_channels,number_of_channels) :: v_mat
real(kind=dp), public, allocatable, dimension(:,:) :: v_tmp
real(kind=dp), public, dimension(number_of_channels,number_of_channels) :: w_mat
real(kind=dp), public, allocatable, dimension(:,:) :: w_tmp
Source Code
      subroutine numerov(channels_level_indices,channels_omega_values,         &
         number_of_nonzero_coupling_matrix_elements,                           &
         number_of_nonzero_coupling_coefficients,nonzero_terms_per_element,    &
         nonzero_legendre_indices,nonzero_coupling_coefficients,nsteps,        &
         number_of_channels,jj,log_der_matrix)
         !! renormalized Numerov propagator
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: number_of_channels
            !! size of the basis
         integer(int32), intent(in) :: channels_level_indices(number_of_channels)
            !! holds the indices pointing to the basis arrays
         integer(int32), intent(in) :: channels_omega_values(number_of_channels)
            !! holds all values of \bar{\Omega}
         integer(int32), intent(in) :: number_of_nonzero_coupling_matrix_elements
            !! number of non-zero terms in the sum () for each non-zero element of the coupling matrix
         integer(int32), intent(in) :: number_of_nonzero_coupling_coefficients
            !! number of all non-zero algberaix coefficients in the whole coupling matrix
         integer(int32), intent(in) :: nonzero_terms_per_element(number_of_nonzero_coupling_matrix_elements)
            !! keeps the number of non-zero terms in the sum (Eq. (6.21)) for
            !! each non-zero element of W/V
         integer(int32), intent(in) :: nonzero_legendre_indices(number_of_nonzero_coupling_coefficients)
            !! holds the proper indices pointing to l1/l2/lltabs, which
            !! correspond to the non-vanishing elements of the sum  (Eq. (6.21))
            !! for each non-zero element of W/V
         real(dp), intent(in) :: nonzero_coupling_coefficients(number_of_nonzero_coupling_coefficients)
            !! holds the values of the non-zero algebraic coefficients
         integer(int32), intent(in) :: nsteps
            !! number of steps from rmin to rmax
         integer(int32), intent(in) :: jj
            !! total angular momentum
         real(dp), intent(inout) :: log_der_matrix(:,:)
            !! resulting log-derivative matrix at RMAX
         !---------------------------------------------------------------------!
         integer(int32) :: i, ii, ij
         real(dp) :: start, finish, r, step_numerov
         real(dp), allocatable, dimension(:,:) :: umatrix, r_temp, rmatrix,    &
            t_minus, t_center, t_plus, r_center, r_plus, w_tmp, v_tmp
         real(dp), dimension(number_of_channels,number_of_channels) ::         &
            cent_mat, v_mat, w_mat, t_mat, u_left, u_right
         !---------------------------------------------------------------------!
         CALL CPU_TIME(start)
         !---------------------------------------------------------------------!
         ! Calculate the centrifugal term
         !---------------------------------------------------------------------!
         call cenitrfugal_matrix(number_of_channels,jj,channels_level_indices, &
            channels_omega_values,cent_mat)
         step_numerov = (rmax - rmin)/dble(nsteps - 1)
         call allocate_2d(R_temp,number_of_channels,number_of_channels)
         !---------------------------------------------------------------------!
         ! Calculate the PES contribution at rmin
         !---------------------------------------------------------------------!
         call pes_contribution(number_of_channels,jj,rmin,                     &
            channels_level_indices,channels_omega_values,                      &
            number_of_nonzero_coupling_matrix_elements,                        &
            number_of_nonzero_coupling_coefficients,                           &
            nonzero_terms_per_element,nonzero_legendre_indices,                &
            nonzero_coupling_coefficients,v_mat)
         !---------------------------------------------------------------------!
         ! Coupling matrix W at rmin
         !---------------------------------------------------------------------!
         w_mat = v_mat - (1./rmin**2.)*cent_mat
         !---------------------------------------------------------------------!
         ! T-matrix (Eq. 6.23)
         !---------------------------------------------------------------------!
         do ii = 1, number_of_channels
            do ij = 1, number_of_channels
               t_mat(ii, ij) = - ((step_numerov**2.)/12.) * (w_mat(ii, ij))
            enddo
            t_mat(ii, ii) = - ((step_numerov**2.)/12.)*&
                                  (2*reducedmass*ETOTAL())+t_mat(ii, ii)
         enddo
         !---------------------------------------------------------------------!
         ! U-matrix (Eq. 6.25)
         !---------------------------------------------------------------------!
         do ii = 1, number_of_channels
            do ij = 1, number_of_channels
               u_left(ii, ij) = - t_mat(ii, ij)
            end do
            u_left(ii, ii) = 1.d0 + u_left(ii, ii)
         end do
         call invert_symmetric_matrix(u_left)
         call fill_symmetric_matrix(u_left, 'u')
         !---------------------------------------------------------------------!
         ! R-matrix at rmin + 1 = U-matrix at rmin
         !---------------------------------------------------------------------!
         do ii = 1, number_of_channels
            do ij = 1, number_of_channels
               r_temp(ii, ij) = 12.d0*u_left(ii, ij)
            enddo
            r_temp(ii, ii) = r_temp(ii, ii) - 10.d0
         enddo
         !---------------------------------------------------------------------!
         ! Continue the propagation to rmax
         !---------------------------------------------------------------------!
         do i=2,nsteps
            !------------------------------------------------------------------!
            ! Coupling matrix W at R
            !------------------------------------------------------------------!
            R = rmin + (i-1)*step_numerov
            call allocate_2d(rmatrix,number_of_channels,number_of_channels)
            call allocate_2d(umatrix,number_of_channels,number_of_channels)
            call pes_contribution(number_of_channels,jj,R,                     &
               channels_level_indices,channels_omega_values,                   &
               number_of_nonzero_coupling_matrix_elements,                     &
               number_of_nonzero_coupling_coefficients,                        &
               nonzero_terms_per_element,nonzero_legendre_indices,             &
               nonzero_coupling_coefficients,v_mat)
            w_mat = v_mat - (1./R**2.)*cent_mat
            !------------------------------------------------------------------!
            ! T-matrix at R (6.18)
            !------------------------------------------------------------------!
            do ii = 1, number_of_channels
               do ij= 1, number_of_channels
                  t_mat(ii, ij) = - ((step_numerov**2.)/12.) * (w_mat(ii, ij))
               enddo
               t_mat(ii, ii) = - ((step_numerov**2.)/12.) *                    &
                  (2*reducedmass*ETOTAL()) + t_mat(ii, ii)
            enddo
            !------------------------------------------------------------------!
            ! U-matrix at R (6.20)
            !------------------------------------------------------------------!
            do ii = 1, number_of_channels
               do ij = 1, number_of_channels
                  u_left(ii, ij) = - t_mat(ii, ij)
               end do
               u_left(ii, ii) = 1.d0 + u_left(ii, ii)
            end do
            call invert_symmetric_matrix(u_left)
            call fill_symmetric_matrix(u_left, 'u')
            do ii = 1, number_of_channels
               do ij = 1, number_of_channels
                  umatrix(ii, ij) = 12.d0*u_left(ii, ij)
               enddo
               umatrix(ii, ii) = umatrix(ii, ii) - 10.d0
            enddo
            call invert_symmetric_matrix(r_temp)
            call fill_symmetric_matrix(r_temp, 'u')
            !------------------------------------------------------------------!
            ! Prepare T at Rmax - 1 and R at Rmax
            !------------------------------------------------------------------!
            if (i == nsteps - 1) then
               call allocate_2d(v_tmp,number_of_channels,number_of_channels)
               call allocate_2d(w_tmp,number_of_channels,number_of_channels)
               call allocate_2d(t_minus,number_of_channels,number_of_channels)
               call pes_contribution(number_of_channels,jj,r,                  &
                  channels_level_indices,channels_omega_values,                &
                  number_of_nonzero_coupling_matrix_elements,                  &
                  number_of_nonzero_coupling_coefficients,                     &
                  nonzero_terms_per_element,nonzero_legendre_indices,          &
                  nonzero_coupling_coefficients,v_tmp)
               w_tmp = v_tmp - (1./R**2.)*cent_mat
               do ii = 1, number_of_channels
                  do ij= 1, number_of_channels
                     t_minus(ii, ij) = -((step_numerov**2.)/12.)*&
                                              (w_tmp(ii, ij))
                  enddo
                  t_minus(ii, ii) = -((step_numerov**2.)/12.) *                &
                     (2*reducedmass*ETOTAL()) + t_minus(ii, ii)
               enddo
               call allocate_2d(r_center,number_of_channels,number_of_channels)
               r_center = umatrix - r_temp
               !---------------------------------------------------------------!
               ! Prepare T at Rmax and R max + 1, and R at Rmax + 1
               !---------------------------------------------------------------!
            else if (i == nsteps) then
               call allocate_2d(v_tmp,number_of_channels,number_of_channels)
               call allocate_2d(w_tmp,number_of_channels,number_of_channels)
               call allocate_2d(t_center,number_of_channels,number_of_channels)
               call pes_contribution(number_of_channels,jj,r,                  &
                  channels_level_indices,channels_omega_values,                &
                  number_of_nonzero_coupling_matrix_elements,                  &
                  number_of_nonzero_coupling_coefficients,                     &
                  nonzero_terms_per_element,nonzero_legendre_indices,          &
                  nonzero_coupling_coefficients,v_tmp)
               w_tmp = v_tmp - (1./R**2.)*cent_mat
               do ii = 1, number_of_channels
                  do ij= 1, number_of_channels
                     t_center(ii, ij) = -((step_numerov**2.)/12.)*             &
                                               (w_tmp(ii, ij))
                  enddo
                  t_center(ii, ii) = -((step_numerov**2.)/12.) *               &
                     (2*reducedmass*ETOTAL()) + t_center(ii, ii)
               enddo
               call allocate_2d(r_plus,number_of_channels,number_of_channels)
               r_plus = umatrix - r_temp
               r = rmax + step_numerov
               call allocate_2d(v_tmp,number_of_channels,number_of_channels)
               call allocate_2d(t_plus,number_of_channels,number_of_channels)
               call allocate_2d(w_tmp,number_of_channels,number_of_channels)
               call pes_contribution(number_of_channels,jj,r,                  &
                  channels_level_indices,channels_omega_values,                &
                  number_of_nonzero_coupling_matrix_elements,                  &
                  number_of_nonzero_coupling_coefficients,                     &
                  nonzero_terms_per_element,nonzero_legendre_indices,          &
                  nonzero_coupling_coefficients,v_tmp)
               w_tmp = v_tmp - (1./R**2.)*cent_mat
               do ii = 1, number_of_channels
                  do ij= 1, number_of_channels
                     t_plus(ii, ij) = -((step_numerov**2.)/12.) *              &
                        (w_tmp(ii, ij))
                  enddo
                  t_plus(ii, ii) = -((step_numerov**2.)/12.) *                 &
                     (2*reducedmass*ETOTAL()) + t_plus(ii, ii)
               enddo
            end if
            !------------------------------------------------------------------!
            ! R-matrix at R_{n+1} (Eq. 6.28)
            !------------------------------------------------------------------!
            rmatrix = umatrix - r_temp
            call allocate_2d(r_temp,number_of_channels,number_of_channels)
            !------------------------------------------------------------------!
            ! Move R_{n+1} to R_{n}
            !------------------------------------------------------------------!
            r_temp = rmatrix
         end do
         CALL CPU_TIME(finish)
         !---------------------------------------------------------------------!
         ! Eq. (6.29)
         !---------------------------------------------------------------------!
         call calculate_log_der_matrix(step_numerov,number_of_channels,        &
            t_minus,t_center,t_plus,r_center,r_plus,log_der_matrix)
         !---------------------------------------------------------------------!
         if (prntlvl.ge.2) then
            call write_message("Numerov propagator took " //                   &
               trim(adjustl(float_to_character(finish-start, "(E14.8)"))) //   &
               " seconds" )
         endif
         !---------------------------------------------------------------------!
      end subroutine numerov
Call graph
numerov calls etotal, calculate_log_der_matrix, write_message, pes_contribution, cenitrfugal_matrix, allocate_2d, invert_symmetric_matrix, fill_symmetric_matrix, float_to_character
calculate_log_der_matrix calls invert_symmetric_matrix, fill_symmetric_matrix, dgemm
pes_contribution calls fill_symmetric_matrix, radtermvalue
cenitrfugal_matrix calls fill_symmetric_matrix, dfloat
radtermvalue calls integer_to_character, ispline, write_error
ispline calls float_to_character, write_warning
write_error calls write_message
write_warning calls write_message
scattering calls numerov