pes_contribution – the SCATTERING code
pes_contribution Subroutine
43 statements
Source File
public subroutine pes_contribution(number_of_channels, jj, r, channels_level_indices, channels_omega_values, number_of_nonzero_coupling_matrix_elements, number_of_nonzero_coupling_coefficients, nonzero_terms_per_element, nonzero_legendre_indices, nonzero_coupling_coefficients, vmatrix)
calculates the contribution from the PES in (X) at given R
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: number_of_channels
size of the basis
integer(kind=int32), intent(in) :: jj
total angular momentum
real(kind=dp), intent(in) :: r
intermolecular distance
integer(kind=int32), intent(in) :: channels_level_indices(number_of_channels)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(in) :: channels_omega_values(number_of_channels)
holds all values of \bar{\Omega}
integer(kind=int32), intent(in) :: number_of_nonzero_coupling_matrix_elements
number of non-zero terms in the sum () for each non-zero element of the coupling matrix
integer(kind=int32), intent(in) :: number_of_nonzero_coupling_coefficients
number of all non-zero algberaix coefficients in the whole coupling matrix
integer(kind=int32), intent(in) :: nonzero_terms_per_element(number_of_nonzero_coupling_matrix_elements)
keeps the number of non-zero terms in the sum (Eq. (6.21)) for each non-zero element of W/V
integer(kind=int32), intent(in) :: nonzero_legendre_indices(number_of_nonzero_coupling_coefficients)
holds the proper indices pointing to l1/l2/lltabs, which correspond to the non-vanishing elements of the sum (Eq. (6.21)) for each non-zero element of W/V
real(kind=dp), intent(in) :: nonzero_coupling_coefficients(number_of_nonzero_coupling_coefficients)
holds the values of the non-zero algebraic coefficients
real(kind=dp), intent(out) :: vmatrix(number_of_channels,number_of_channels)
(output) - the PES contribution to the coupling matrix
Calls
Called by
Contents
Variables
erot ii ij il indvl inonzero_coupling_matrix_elements j1ptmp j1tmp l1 nonzerolam omegaptmp omegatmp pscoeff sumtemp v v1ptmp v1tmp
Source Code
pes_contribution
Variables
Type Visibility Attributes Name Initial
real(kind=dp), public :: erot
integer(kind=int32), public :: ii
integer(kind=int32), public :: ij
integer(kind=int32), public :: il
integer(kind=int32), public :: indvl
integer(kind=int32), public :: inonzero_coupling_matrix_elements
integer(kind=int32), public :: j1ptmp
integer(kind=int32), public :: j1tmp
integer(kind=int32), public :: l1
integer(kind=int32), public :: nonzerolam
integer(kind=int32), public :: omegaptmp
integer(kind=int32), public :: omegatmp
real(kind=dp), public :: pscoeff
real(kind=dp), public :: sumtemp
real(kind=dp), public :: v
integer(kind=int32), public :: v1ptmp
integer(kind=int32), public :: v1tmp
Source Code
      subroutine pes_contribution(number_of_channels,jj,r,                     &
         channels_level_indices,channels_omega_values,                         &
         number_of_nonzero_coupling_matrix_elements,                           &
         number_of_nonzero_coupling_coefficients,                              &
         nonzero_terms_per_element,nonzero_legendre_indices,                   &
         nonzero_coupling_coefficients,vmatrix)
         !! calculates the contribution from the PES in (X) at given R
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: number_of_channels
            !! size of the basis
         integer(int32), intent(in) :: jj
            !! total angular momentum
         real(dp), intent(in) :: r
            !! intermolecular distance
         integer(int32), intent(in) :: channels_level_indices(number_of_channels)
            !! holds the indices pointing to the basis arrays
         integer(int32), intent(in) :: channels_omega_values(number_of_channels)
            !! holds all values of \bar{\Omega}
         integer(int32), intent(in) :: number_of_nonzero_coupling_matrix_elements
            !! number of non-zero terms in the sum () for each non-zero element of the coupling matrix
         integer(int32), intent(in) :: number_of_nonzero_coupling_coefficients
            !! number of all non-zero algberaix coefficients in the whole coupling matrix
         integer(int32), intent(in) :: nonzero_terms_per_element(number_of_nonzero_coupling_matrix_elements)
            !! keeps the number of non-zero terms in the sum (Eq. (6.21)) for
            !! each non-zero element of W/V
         integer(int32), intent(in) :: nonzero_legendre_indices(number_of_nonzero_coupling_coefficients)
            !! holds the proper indices pointing to l1/l2/lltabs, which
            !! correspond to the non-vanishing elements of the sum  (Eq. (6.21))
            !! for each non-zero element of W/V
         real(dp), intent(in) :: nonzero_coupling_coefficients(number_of_nonzero_coupling_coefficients)
            !! holds the values of the non-zero algebraic coefficients
         real(dp), intent(out) :: vmatrix(number_of_channels, number_of_channels)
            !! (output) - the PES contribution to the coupling matrix
         !---------------------------------------------------------------------!
         integer(int32) :: indvl, inonzero_coupling_matrix_elements, omegatmp, omegaptmp, l1,          &
            nonzerolam, v1tmp, j1tmp, v1ptmp, j1ptmp, ii, ij, il
         real(dp) :: erot, sumtemp, pscoeff, v
         !---------------------------------------------------------------------!
         vmatrix   = 0
         indvl     = 0
         inonzero_coupling_matrix_elements = 0
         !---------------------------------------------------------------------!
         do ii = 1, number_of_channels
            v1tmp    = v1array(channels_level_indices(ii))
            j1tmp    = j1array(channels_level_indices(ii))
            omegatmp = channels_omega_values(ii)
            erot     = elevel(channels_level_indices(ii))
            do ij = 1, ii
               v1ptmp    = v1array(channels_level_indices(ij))
               j1ptmp    = j1array(channels_level_indices(ij))
               omegaptmp = channels_omega_values(ij)
               if (omegatmp.ne.omegaptmp) cycle
               inonzero_coupling_matrix_elements  = inonzero_coupling_matrix_elements + 1
               nonzerolam = nonzero_terms_per_element(inonzero_coupling_matrix_elements)
               sumtemp    = 0.d0
               do il = 1, nonzerolam
                  indvl   = indvl+1
                  l1      = l1tab(nonzero_legendre_indices(indvl))
                  pscoeff = nonzero_coupling_coefficients(indvl)
                  call RADTERMVALUE(r,l1,v1tmp,j1tmp,v1ptmp,j1ptmp,v)
                  sumtemp = sumtemp+pscoeff*v
               enddo
               vmatrix(ii,ij) = -2*reducedmass*sumtemp
             enddo
             vmatrix(ii,ii) = vmatrix(ii,ii)-(2*reducedmass*erot)
         enddo
         !---------------------------------------------------------------------!
         call fill_symmetric_matrix(vmatrix,'u')
         !---------------------------------------------------------------------!
      end subroutine pes_contribution
Call graph
pes_contribution calls radtermvalue, fill_symmetric_matrix
radtermvalue calls integer_to_character, write_error, ispline
write_error calls write_message
ispline calls write_warning, float_to_character
write_warning calls write_message
numerov calls pes_contribution
scattering calls numerov