potential_read – the SCATTERING code
potential_read Subroutine
32 statements
Source File
public subroutine potential_read()
reads the radial coupling terms from the external file. The file is assumed to be formatted as follows: R, V_{l1,v1,j1,v1',j1'}(R) The read radial coupling terms are kept in vmat/read_vmat3D
Arguments
None
Calls
Called by
Contents
Variables
err_message icol il io_status ir iskip_ l1 nrtmp
Variables
Type Visibility Attributes Name Initial
character(len=200), public :: err_message
integer(kind=int32), public :: icol
integer(kind=int32), public :: il
integer(kind=int32), public :: io_status
integer(kind=int32), public :: ir
integer(kind=int32), public :: iskip_
integer(kind=int32), public :: l1
integer(kind=int32), public :: nrtmp
Call graph
potential_read calls file_io_status, integer_to_character, float_to_character, write_error
file_io_status calls integer_to_character, write_error
write_error calls write_message
scattering calls potential_read