potential_reduction – the SCATTERING code
potential_reduction Subroutine
35 statements
Source File
public subroutine potential_reduction()
reducesof the read_vmat3D matrix to retain only the necessary coupling terms which are kept in reduced_*. The number of necessary coupling terms (ncoupl) is already determined in io_mod module. If totalcol = ncoupl, the procedure is ignored
Arguments
None
Calls
Called by
Contents
Variables
icol icoupl il ir
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: icol
integer(kind=int32), public :: icoupl
integer(kind=int32), public :: il
integer(kind=int32), public :: ir
Call graph
potential_reduction calls write_message, integer_to_character
scattering calls potential_reduction