print_detailed_cross_section_info – the SCATTERING code
print_detailed_cross_section_info Subroutine
13 statements
Source File
private subroutine print_detailed_cross_section_info(total_angular_momentum_, cross_section_value_, index_1_, index_2_, open_basis_levels_, type_label_)
Prints detailed information about the largest elastic and inelastic state-to-state xs (print_level >= 3)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: total_angular_momentum_
total angular momentum
real(kind=dp), intent(in) :: cross_section_value_
value of the cross-section
integer(kind=int32), intent(in) :: index_1_
indices pointing indirectly to quantum numbers associated with the largest partial XS in the block
integer(kind=int32), intent(in) :: index_2_
indices pointing indirectly to quantum numbers associated with the largest partial XS in the block
integer(kind=int32), intent(in) :: open_basis_levels_(:)
array holding indices to open basis levels
character(len=*), intent(in) :: type_label_
"elastic" or "inelastic"
Calls
Called by
Contents
Variables
header_line_ line_
Source Code
print_detailed_cross_section_info
Variables
Type Visibility Attributes Name Initial
character(len=200), private :: header_line_
character(len=200), private :: line_
Source Code
      subroutine print_detailed_cross_section_info(total_angular_momentum_,    &
         cross_section_value_, index_1_, index_2_, open_basis_levels_,         &
         type_label_)
         !! Prints detailed information about the largest elastic and inelastic
         !! state-to-state xs (print_level >= 3)
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: total_angular_momentum_
            !! total angular momentum
         integer(int32), intent(in) :: index_1_, index_2_
            !! indices pointing indirectly to quantum numbers associated with
            !! the largest partial XS in the block
         real(dp), intent(in) :: cross_section_value_
            !! value of the cross-section
         integer(int32), intent(in) :: open_basis_levels_(:)
            !! array holding indices to open basis levels
         character(len=*), intent(in) :: type_label_
            !! "elastic" or "inelastic"
         !---------------------------------------------------------------------!
         character(len=200) :: header_line_, line_
         !---------------------------------------------------------------------!
         call write_message("Largest partial " // trim(type_label_) //         &
            " state-to-state for JTOT = " //                                   &
            trim(adjustl(integer_to_character(total_angular_momentum_))))
         write(header_line_, "(2x,a4,2x,a4,2x,a2,2x,a4,2x,a4,16x,a2)")         &
            "v1_f", "j1_f", "<-", "v1_i", "j1_i", "XS"
         call write_message(header_line_)
         !---------------------------------------------------------------------!
         write(line_, "(2X,I4,2X,I4,6X,I4,2X,I4,2X,E16.8)")                    &
           vib_levels(open_basis_levels_(index_1_)),                           &
           rot_levels(open_basis_levels_(index_1_)),                           &
           vib_levels(open_basis_levels_(index_2_)),                           &
           rot_levels(open_basis_levels_(index_2_)), cross_section_value_
         call write_message(line_)
         !---------------------------------------------------------------------!
      end subroutine print_detailed_cross_section_info
Call graph
print_detailed_cross_section_info calls integer_to_character, write_message
print_largest_partial_cross_sections calls print_detailed_cross_section_info
scattering calls print_largest_partial_cross_sections