print_basic_cross_section_info – the SCATTERING code
print_basic_cross_section_info Subroutine
6 statements
Source File
private subroutine print_basic_cross_section_info(total_angular_momentum_, cross_section_value_, type_label_)
Prints basic information about the largest elastic and inelastic state-to-state xs (print_level <= 2)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: total_angular_momentum_
total angular momentum
real(kind=dp), intent(in) :: cross_section_value_
value of the cross-section
character(len=*), intent(in) :: type_label_
"elastic" or "inelastic"
Calls
Called by
Contents
Source Code
print_basic_cross_section_info
Source Code
      subroutine print_basic_cross_section_info(total_angular_momentum_,       &
         cross_section_value_, type_label_)
         !! Prints basic information about the largest elastic and inelastic
         !! state-to-state xs (print_level <= 2)
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: total_angular_momentum_
            !! total angular momentum
         real(dp), intent(in) :: cross_section_value_
            !! value of the cross-section
         character(len=*), intent(in) :: type_label_
            !! "elastic" or "inelastic"
         !---------------------------------------------------------------------!
         call write_message(" - Largest partial " // trim(type_label_) //     &
            " state-to-state for JTOT = " //                                   &
            trim(adjustl(integer_to_character(total_angular_momentum_))) //    &
            ": " // trim(adjustl(float_to_character(cross_section_value_))))
         !---------------------------------------------------------------------!
      end subroutine print_basic_cross_section_info
Call graph
print_basic_cross_section_info calls integer_to_character, write_message, float_to_character
print_largest_partial_cross_sections calls print_basic_cross_section_info
scattering calls print_largest_partial_cross_sections