read_and_validate_lambda – the SCATTERING code
read_and_validate_lambda Subroutine
11 statements
Source File
private subroutine read_and_validate_lambda(lambda_index_)
Reads the value of lambda and compares with expected value.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: lambda_index_
Calls
Called by
Contents
Variables
lambda_
Source Code
read_and_validate_lambda
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: lambda_
Source Code
      subroutine read_and_validate_lambda(lambda_index_)
         !! Reads the value of lambda and compares with expected value.
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: lambda_index_
         !---------------------------------------------------------------------!
         integer(int32) :: lambda_
         !---------------------------------------------------------------------!
         read (coupling_terms_file_unit, *) lambda_
         if (lambda_.ne.legendre_indices(lambda_index_)) then
            close(coupling_terms_file_unit)
            close(s_matrix_unit)
            if (print_partial_cross_sections) close(partial_file_unit)
            call write_error("read_radial_coupling_terms: lambda = " //        &
               trim(adjustl(integer_to_character(lambda_))) //                 &
               " differs from expected value in legendre_indices (" //         &
               trim(adjustl(integer_to_character(lambda_index_))) // ") = " // &
               trim(adjustl(integer_to_character(legendre_indices(lambda_index_)))))
         endif
         !---------------------------------------------------------------------!
      end subroutine read_and_validate_lambda
Call graph
read_and_validate_lambda calls integer_to_character, write_error
write_error calls write_message
read_radial_coupling_terms calls read_and_validate_lambda
scattering calls read_radial_coupling_terms