save_partial_xs_file_header – the SCATTERING code
save_partial_xs_file_header Subroutine
7 statements
Source File
public subroutine save_partial_xs_file_header()
save "header" of the partial cross-sections file: -- label, "itype", number of levels in the basis, reduced mass of the system -- vibrational and rotational quantum numbers -- rovibrational energies -- index pointing to the initial level and the kinetic/total energy
Arguments
None
Calls
Called by
Contents
Source Code
save_partial_xs_file_header
Source Code
      subroutine save_partial_xs_file_header
         !! save "header" of the partial cross-sections file:
         !! -- label, "itype", number of levels in the basis, reduced mass of the system
         !! -- vibrational and rotational quantum numbers
         !! -- rovibrational energies
         !! -- index pointing to the initial level and the kinetic/total energy
         !---------------------------------------------------------------------!
         character(len=200) :: err_message
         integer(int32) :: io_status, ilevel
         !---------------------------------------------------------------------!
         open(partial_file_unit, file=trim(partialfile),form='formatted',      &
            status='unknown', iostat = io_status, iomsg = err_message)
         call file_io_status(io_status, err_message, partial_file_unit, "o")
         !---------------------------------------------------------------------!
         call write_message( "  jtot  iblock  v1_f  j1_f  <-  v1_i  j1_i'" //  &
            repeat(" ", 13) // "K.E." // repeat(" ", 16) // "XS",              &
            unit_ = partial_file_unit)
         !---------------------------------------------------------------------!
      end subroutine save_partial_xs_file_header
Call graph
save_partial_xs_file_header calls file_io_status, write_message
file_io_status calls integer_to_character, write_error
write_error calls write_message
scattering calls save_partial_xs_file_header