set_channels_level_indices_channels_omega_values – the SCATTERING code
set_channels_level_indices_channels_omega_values Subroutine
33 statements
Source File
public subroutine set_channels_level_indices_channels_omega_values(number_of_channels, jtot_, nparity, channels_level_indices, channels_omega_values)
Prepares the channels_level_indices array which holds indices that refer to the basis arrays: v1level/j1level/elevel, and channels_omega_values which holds values of \bar{\Omega}
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: number_of_channels
number of channels in the block
integer(kind=int32), intent(in) :: jtot_
total angular momentum
integer(kind=int32), intent(in) :: nparity
parity exponent of the block (0 if p = +1, 1 if p = -1)
integer(kind=int32), intent(inout) :: channels_level_indices(number_of_channels)
holds the indices pointing to the basis arrays
integer(kind=int32), intent(inout) :: channels_omega_values(number_of_channels)
holds all values of \bar{\Omega}
Calls
Called by
Contents
Variables
ij iomega isize_ omegamax omegatmp
Source Code
set_channels_level_indices_channels_omega_values
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: ij
integer(kind=int32), public :: iomega
integer(kind=int32), public :: isize_
integer(kind=int32), public :: omegamax
integer(kind=int32), public :: omegatmp
Source Code
      subroutine set_channels_level_indices_channels_omega_values(number_of_channels, jtot_, nparity, channels_level_indices,   &
         channels_omega_values)
         !! Prepares the channels_level_indices array which holds indices that refer to the
         !! basis arrays: v1level/j1level/elevel, and channels_omega_values which holds values
         !! of \bar{\Omega}
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: number_of_channels
            !! number of channels in the block
         integer(int32), intent(in) :: jtot_
            !! total angular momentum
         integer(int32), intent(in) :: nparity
            !! parity exponent of the block (0 if p = +1, 1 if p = -1)
         integer(int32), intent(inout) :: channels_level_indices(number_of_channels)
            !! holds the indices pointing to the basis arrays
         integer(int32), intent(inout) :: channels_omega_values(number_of_channels)
            !! holds all values of \bar{\Omega}
         !---------------------------------------------------------------------!
         integer(int32) :: isize_, omegatmp, omegamax, ij, iomega
         !---------------------------------------------------------------------!
         isize_ = 0
         !---------------------------------------------------------------------!
         do ij = 1,nlevel
            omegamax = min(j1array(ij), jtot_)
            if (nparity.eq.0) then
               do iomega = 1, omegamax + 1
                  if (isize_ >= number_of_channels) then
                     call write_error("Array index isize_ out of bounds of " //      &
                        "channels_l_values in set_channels_level_indices_channels_omega_values.")
                  end if
                  omegatmp = iomega - 1
                  channels_omega_values(isize_ + 1) = omegatmp
                  channels_level_indices(isize_ + 1) = ij
                  isize_ = isize_ + 1
               enddo
            else
               do iomega = 1, omegamax
                  if (isize_ >= number_of_channels) then
                     call write_error("Array index isize_ out of bounds of " //      &
                        "channels_l_values in set_channels_level_indices_channels_omega_values.")
                  end if
                  omegatmp = iomega
                  channels_omega_values(isize_ + 1) = omegatmp
                  channels_level_indices(isize_ + 1) = ij
                  isize_ = isize_ + 1
               enddo
            endif
          enddo
         !---------------------------------------------------------------------!
      end subroutine set_channels_level_indices_channels_omega_values
Call graph
set_channels_level_indices_channels_omega_values calls write_error
write_error calls write_message
scattering calls set_channels_level_indices_channels_omega_values