to_lowercase – the SCATTERING code
to_lowercase Function
8 statements
Source File
public function to_lowercase(str) result(low_str)
forces lowercase on given string
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: str
input string
Return Value character(len=len)
output (lowercase) string
Calls
Called by
Contents
Variables
i
Source Code
to_lowercase
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: i
Source Code
      function to_lowercase(str) result(low_str)
         !! forces lowercase on given string
         !---------------------------------------------------------------------!
         character(len=*), intent(in) :: str
            !! input string
         character(len=len(str))      :: low_str
            !! output (lowercase) string
         !---------------------------------------------------------------------!
         integer(int32)               :: i
         !---------------------------------------------------------------------!
         do i = 1, len(str)
            low_str(i:i) = char_to_lowercase(str(i:i))
         enddo
         !---------------------------------------------------------------------!
      end function to_lowercase
Call graph
to_lowercase calls char_to_lowercase
check_namelist_input calls to_lowercase
fill_symmetric_matrix_sp calls to_lowercase
fill_symmetric_matrix_int32 calls to_lowercase
read_input_file calls to_lowercase, check_namelist_input
fill_symmetric_matrix_dp calls to_lowercase
scattering calls read_input_file