total_energy – the SCATTERING code
total_energy Function
8 statements
Source File
public function total_energy() result(etot_)
returns the total energy
Arguments
None
Return Value real(kind=dp)
Called by
Contents
Source Code
total_energy
Source Code
      function total_energy() result(etot_)
         !! returns the total energy
         !---------------------------------------------------------------------!
         real(dp) ::  etot_
         !---------------------------------------------------------------------!
         if (relative_energy_flag.eq.0) then
            etot_ = energy
         else if (relative_energy_flag.eq.1) then
            etot_ = energy+internal_energies(initial_level)
         endif
         !---------------------------------------------------------------------!
      end function total_energy
Call graph
wavevector_squared_from_energy calls total_energy
print_cross_sections_for_jtot calls total_energy, print_all_cross_sections
save_partial_xs_single_block calls total_energy
input_summary calls total_energy
is_open calls total_energy
print_all_cross_sections calls total_energy
prepare_wavevector_array calls wavevector_squared_from_energy, is_open
print_channels calls wavevector_squared_from_energy, is_open
read_input_file calls input_summary
count_open_basis_levels calls is_open
save_open_basis_levels calls wavevector_squared_from_energy, is_open
calculate_single_pes_matrix_element calls wavevector_squared_from_energy
calculate_largest_wavevector calls wavevector_squared_from_energy, is_open
calculate_k_matrix calls wavevector_squared_from_energy, is_open
scattering calls print_cross_sections_for_jtot, save_partial_xs_single_block, prepare_wavevector_array, print_channels, read_input_file, count_open_basis_levels, save_open_basis_levels, calculate_largest_wavevector, calculate_k_matrix, count_open_channels_in_block, print_final_cross_sections
count_open_channels_in_block calls is_open
print_final_cross_sections calls print_all_cross_sections
calculate_pes_matrix calls calculate_single_pes_matrix_element
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix
numerov calls initial_setup, general_propagation_step
handle_final_propagation_steps calls general_propagation_step