unitarity_check – the SCATTERING code
unitarity_check Subroutine
47 statements
Source File
public subroutine unitarity_check(number_of_open_channels, s_matrix_real, s_matrix_imag, totalcheck)
checks the unitarity of the S-matrix (Eq. 6.15)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: number_of_open_channels
number of open channels
real(kind=dp), intent(in) :: s_matrix_real(number_of_open_channels,number_of_open_channels)
real part of the S-matrix
real(kind=dp), intent(in) :: s_matrix_imag(number_of_open_channels,number_of_open_channels)
imaginary part of the S-matrix
logical, intent(inout) :: totalcheck
(output) if .true. unitary is fulfilled, .false. otherwise
Calls
Called by
Contents
Variables
iopen iopen2 line_ unitary_tol unitarycheck unitarychecktmp
Source Code
unitarity_check
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), public :: iopen
integer(kind=int32), public :: iopen2
character(len=200), public :: line_
real(kind=dp), public :: unitary_tol
real(kind=dp), public :: unitarycheck(number_of_open_channels)
real(kind=dp), public :: unitarychecktmp
Source Code
      subroutine unitarity_check(number_of_open_channels,s_matrix_real,        &
         s_matrix_imag,totalcheck)
         !! checks the unitarity of the S-matrix (Eq. 6.15)
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: number_of_open_channels
            !! number of open channels
         real(dp), intent(in) :: s_matrix_real(number_of_open_channels,number_of_open_channels)
            !! real part of the S-matrix
         real(dp), intent(in) :: s_matrix_imag(number_of_open_channels,number_of_open_channels)
            !! imaginary part of the S-matrix
         logical, intent(inout) :: totalcheck
            !! (output) if .true. unitary is fulfilled, .false. otherwise
         !---------------------------------------------------------------------!
         character(len = 200) :: line_
         integer(int32) :: iopen, iopen2
         real(dp) :: unitarychecktmp, unitary_tol
         real(dp) :: unitarycheck(number_of_open_channels)
         !---------------------------------------------------------------------!
         totalcheck  = .true.
         unitary_tol = 1e-6_dp
         !---------------------------------------------------------------------!
         if (prntlvl.ge.4) then
            call write_message("Check of the unitarity of the S-matrix:")
            call write_message(repeat(" ", 34) // "*** S-matrix elements: ***")
            call write_message("   ROW   COL" // repeat(" ", 15) // "S**2" //  &
               repeat(" ", 17) // "RE (S)" // repeat(" ", 17) // "IM (S)")
         endif
         !---------------------------------------------------------------------!
         do iopen=1, number_of_open_channels
            unitarychecktmp = 0.0_dp
            do iopen2=1, number_of_open_channels
               unitarychecktmp = unitarychecktmp +                             &
                  s_matrix_real(iopen,iopen2)**2. + s_matrix_imag(iopen,iopen2)**2.
               !---------------------------------------------------------------!
               if (prntlvl.ge.4) then
                  write(line_, "(1X,I5,1X,I5,8X,E15.8,8X,E15.8,8X,E15.8)")     &
                     iopen, iopen2, s_matrix_real(iopen,iopen2)**2.+s_matrix_imag(iopen,iopen2)**2.,  &
                     s_matrix_real(iopen,iopen2), s_matrix_imag(iopen,iopen2)
                  call write_message(line_)
               endif
               !---------------------------------------------------------------!
            enddo
            unitarycheck(iopen) = unitarychecktmp
         enddo
         !---------------------------------------------------------------------!
         do iopen=1, number_of_open_channels
            if (dabs(unitarycheck(iopen)-1.d0).gt.unitary_tol) then
               call write_warning("Unitary condition is not fulfilled for channel no.")
               write(line_, "(1X,I5,8X,E15.8)") iopen, unitarycheck(iopen)
               call write_message(trim(adjustl(line_)))
               call write_message("Consider increasing the STEPS parameter")
               totalcheck = .false.
            endif
         enddo
         if (prntlvl.ge.4) then
            call write_message(repeat(" ", 43) // "***")
            call write_message("Check of the unitarity of the S-matrix:")
            call write_message("   ROW" // repeat(" ", 12) // "sum(S**2)")
            do iopen=1, number_of_open_channels
               write(line_, "(1X,I5,8X,E15.8)") iopen, unitarycheck(iopen)
               call write_message(trim(adjustl(line_)))
            enddo
            call write_message(repeat(" ", 43) // "***")
         endif
         !---------------------------------------------------------------------!
      end subroutine unitarity_check
Call graph
unitarity_check calls write_message, write_warning
write_warning calls write_message
scattering calls unitarity_check