wavevector_squared_from_energy – the SCATTERING code
wavevector_squared_from_energy Function
9 statements
Source File
public function wavevector_squared_from_energy(energy_) result(k_)
returns the squared wavevector, \(k_{a}^{2}\), given the energy of a given state, \(E_{a}\); calls etot() function; atomic units in the whole function \(k_{a} = \sqrt(2 \mu (E_{tot} - E_{a}) \) since it uses reduced_mass and total_energy(), the function checks if units are already converted
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: energy_
energy of a given state, \(E_{a} \), in a.u.
Return Value real(kind=dp)
wavevector, \(k_{a}\), in a.u.
Calls
Called by
Contents
Source Code
wavevector_squared_from_energy
Source Code
      function wavevector_squared_from_energy(energy_) result(k_)
         !! returns the squared wavevector, \\(k_{a}^{2}\\),
         !! given the energy of a given state, \\(E_{a}\\);
         !! calls etot() function; atomic units in the whole function
         !! \\( k_{a} = \sqrt(2 \mu (E_{tot} - E_{a}) \\)
         !! since it uses reduced_mass and total_energy(), the function checks
         !! if units are already converted
         !---------------------------------------------------------------------!
         real(dp), intent(in) :: energy_
            !! energy of a given state, \\( E_{a} \\), in a.u.
         real(dp) :: k_
            !! wavevector, \\(k_{a}\\), in a.u.
         !---------------------------------------------------------------------!
         if (units_converted) then
            k_ = 2*reduced_mass*(total_energy() - energy_)
         else
            call write_error("wavevector_squared_from_energy called " //       &
               "but units are not converted yet")
         endif
         !---------------------------------------------------------------------!
      end function wavevector_squared_from_energy
Call graph
wavevector_squared_from_energy calls total_energy, write_error
write_error calls write_message
prepare_wavevector_array calls wavevector_squared_from_energy
print_channels calls wavevector_squared_from_energy
save_open_basis_levels calls wavevector_squared_from_energy
calculate_single_pes_matrix_element calls wavevector_squared_from_energy
calculate_largest_wavevector calls wavevector_squared_from_energy
calculate_k_matrix calls wavevector_squared_from_energy
scattering calls prepare_wavevector_array, print_channels, save_open_basis_levels, calculate_largest_wavevector, calculate_k_matrix, numerov
calculate_pes_matrix calls calculate_single_pes_matrix_element
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix
numerov calls initial_setup, general_propagation_step, handle_final_propagation_steps
handle_final_propagation_steps calls general_propagation_step