wavenumber_squared_from_energy – the SCATTERING code
wavenumber_squared_from_energy Function
9 statements
Source File
public function wavenumber_squared_from_energy(energy_) result(k_)
returns the squared wavenumber, \(k_{a}^{2}\), given the energy of a given state, \(E_{a}\); calls etot() function; atomic units in the whole function \(k_{a} = \sqrt(2 \mu (E_{tot} - E_{a}) \) since it uses reducedmass and etotal(), the function checks if units are already converted
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: energy_
energy of a given state, \(E_{a} \), in a.u.
Return Value real(kind=dp)
wavenumber, \(k_{a}\), in a.u.
Calls
Called by
Contents
Source Code
wavenumber_squared_from_energy
Source Code
   function wavenumber_squared_from_energy(energy_) result(k_)
      !! returns the squared wavenumber, \\(k_{a}^{2}\\),
      !! given the energy of a given state, \\(E_{a}\\);
      !! calls etot() function; atomic units in the whole function
      !! \\( k_{a} = \sqrt(2 \mu (E_{tot} - E_{a}) \\)
      !! since it uses reducedmass and etotal(), the function checks
      !! if units are already converted
      !------------------------------------------------------------------------!
      real(dp), intent(in) :: energy_
         !! energy of a given state, \\( E_{a} \\), in a.u.
      real(dp) :: k_
         !! wavenumber, \\(k_{a}\\), in a.u.
      !------------------------------------------------------------------------!
      if (units_converted) then
         !---------------------------------------------------------------------!
         ! abs() is for closed channels, see...
         !---------------------------------------------------------------------!
         k_ = 2*reducedmass*(ETOTAL() - energy_)
      else
         call write_error("wavenumber_squared_from_energy called but units are not " //&
            "converted yet")
      endif
      !------------------------------------------------------------------------!
   end function wavenumber_squared_from_energy
Call graph
wavenumber_squared_from_energy calls etotal, write_error
write_error calls write_message
save_open_basis_levels calls wavenumber_squared_from_energy
calculate_k_matrix calls wavenumber_squared_from_energy
calculate_single_pes_matrix_element calls wavenumber_squared_from_energy
calculate_largest_wavenumber calls wavenumber_squared_from_energy
print_channels calls wavenumber_squared_from_energy
scattering calls save_open_basis_levels, calculate_k_matrix, calculate_largest_wavenumber, print_channels, numerov
pes_contribution calls calculate_single_pes_matrix_element
numerov calls pes_contribution