wavenumber_from_energy – the SCATTERING code
wavenumber_from_energy Function
9 statements
Source File
public function wavenumber_from_energy(energy_) result(k_)
returns the wavenumber, \(k_{a}\), given the energy of a given state, \(E_{a}\); calls etot() function; atomic units in the whole function \(k_{a} = \sqrt(2 \mu (E_{tot} - E_{a}) \) since it uses reducedmass and etotal(), the function checks if units are already converted
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(in) :: energy_
energy of a given state, \(E_{a} \), in a.u.
Return Value real(kind=dp)
wavenumber, \(k_{a}\), in a.u.
Calls
Called by
Contents
Call graph
wavenumber_from_energy calls etotal, write_error
write_error calls write_message
save_open_basis_levels calls wavenumber_from_energy
calculate_largest_wavenumber calls wavenumber_from_energy
print_channels calls wavenumber_from_energy
calculate_k_matrix calls wavenumber_from_energy
scattering calls save_open_basis_levels, calculate_largest_wavenumber, print_channels, calculate_k_matrix