write_message – the SCATTERING code
write_message Subroutine
9 statements
Source File
public subroutine write_message(message_, unit_)
writes a message on a chosen unit
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message_
a message to be written
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
Called by
Contents
Source Code
write_message
Source Code
      subroutine write_message(message_, unit_)
         !! writes a message on a chosen unit
         !---------------------------------------------------------------------!
         character(len = *), intent(in)       :: message_
            !! a message to be written
         integer(int32), optional, intent(in) :: unit_
            !! optional, unit where the message will be written
         !---------------------------------------------------------------------!
         if (present(unit_)) then
            write(unit_, '(a)') trim(message_)
         else
            write(output_unit, '(a)') trim(message_)
         endif
         !---------------------------------------------------------------------!
      end subroutine write_message
Call graph
print_final_unitarity_warning calls write_message
print_detailed_cross_section_info calls write_message
save_partial_xs_single_block calls write_message
fill_symmetric_matrix_int32 calls write_message, write_error
reduce_radial_coupling_terms calls write_message, print_pes_quantum_numbers
time_count_summary calls write_message
no_open_channels_message calls write_message
print_short_block_summary calls write_message
print_all_cross_sections calls write_message
print_basic_cross_section_info calls write_message
scattering calls write_message, print_final_unitarity_warning, save_partial_xs_single_block, reduce_radial_coupling_terms, time_count_summary, no_open_channels_message, print_short_block_summary, read_input_file, print_channels, unitarity_check, print_cross_sections_for_jtot, write_header, save_partial_xs_file_header, print_final_cross_sections, print_largest_partial_cross_sections, numerov, calculate_state_to_state_cross_section, set_space_fixed_channels, prepare_wavevector_array, initialize_pes_matrix, interpolate_radial_coupling_terms, set_body_fixed_channels, set_number_of_channels, calculate_k_matrix, read_radial_coupling_terms, save_s_matrix_file_header, save_open_basis_levels, calculate_largest_wavevector
read_input_file calls write_message, input_summary, check_namelist_input, file_io_status, check_namelist_potential, check_namelist_basis
input_summary calls write_message
print_channels calls write_message, write_channel_line, wavevector_squared_from_energy
invert_symmetric_matrix_dp calls write_message, write_error
invert_symmetric_matrix_sp calls write_message, write_error
fill_symmetric_matrix_sp calls write_message, write_error
write_warning calls write_message
unitarity_check calls write_message, handle_unitarity_output_message
print_sum_of_squares calls write_message
fill_symmetric_matrix_dp calls write_message, write_error
print_pes_matrix_elements_summary calls write_message
print_cross_sections_for_jtot calls write_message, print_all_cross_sections
handle_unitarity_output_message calls write_message, write_warning, print_sum_of_squares
write_header calls write_message, write_error, incorrect_value
save_partial_xs_file_header calls write_message, file_io_status
write_error calls write_message
check_namelist_input calls write_message, write_error, incorrect_value
print_pes_quantum_numbers calls write_message
propagator_summary calls write_message
write_channel_line calls write_message
print_final_cross_sections calls write_message, print_all_cross_sections
spline calls write_error
update_body_fixed_channels_info calls write_error
riccati_bessel_j calls write_warning
handle_coupling_index_error calls write_error
incorrect_value_dp calls write_error
riccati_bessel_y calls write_warning
file_io_status calls write_error
validate_r_range calls write_error
incorrect_value_int32 calls write_error
print_largest_partial_cross_sections calls print_detailed_cross_section_info, print_basic_cross_section_info
numerov calls time_count_summary, propagator_summary
calculate_state_to_state_cross_section calls time_count_summary
set_space_fixed_channels calls write_error
ispline calls write_warning
wavevector_squared_from_energy calls write_error
alloc_status calls write_error
prepare_wavevector_array calls write_error, wavevector_squared_from_energy
invert_symmetric_matrix_int32 calls write_error
incorrect_value_ch calls write_error
initialize_pes_matrix calls time_count_summary, print_pes_matrix_elements_summary
incorrect_value_sp calls write_error
modified_bessel_temme_algorithm calls write_error
handle_lambda_index_error calls write_error
read_and_validate_lambda calls write_error
check_number_of_channels calls write_error
interpolate_radial_coupling_terms calls spline
set_body_fixed_channels calls update_body_fixed_channels_info
modified_bessel_k_ratio calls modified_bessel_temme_algorithm
set_number_of_channels calls check_number_of_channels
get_radial_coupling_term_value calls handle_coupling_index_error, ispline, handle_lambda_index_error
calculate_k_matrix calls riccati_bessel_j, riccati_bessel_y, wavevector_squared_from_energy, modified_bessel_k_ratio
incorrect_value calls incorrect_value_dp, incorrect_value_int32, incorrect_value_ch, incorrect_value_sp
read_radial_coupling_terms calls file_io_status, validate_r_range, read_and_validate_lambda
save_s_matrix_file_header calls file_io_status
calculate_single_pes_matrix_element calls wavevector_squared_from_energy, get_radial_coupling_term_value
save_open_basis_levels calls wavevector_squared_from_energy
calculate_largest_wavevector calls wavevector_squared_from_energy
check_namelist_potential calls incorrect_value
calculate_pes_matrix calls calculate_single_pes_matrix_element
check_namelist_basis calls incorrect_value
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix