write_error – the SCATTERING code
write_error Subroutine
6 statements
Source File
public subroutine write_error(message_, unit_)
writes an error message on a chosen unit
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message_
a message to be written
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
Calls
Called by
Contents
Source Code
write_error
Source Code
      subroutine write_error(message_, unit_)
         !! writes an error message on a chosen unit
         !---------------------------------------------------------------------!
         character(len = *), intent(in)       :: message_
            !! a message to be written
         integer(int32), optional, intent(in) :: unit_
            !! optional, unit where the message will be written
         !---------------------------------------------------------------------!
         call write_message('Error: '//trim(message_), unit_)
         stop
         !---------------------------------------------------------------------!
      end subroutine write_error
Call graph
write_error calls write_message
validate_r_range calls write_error
incorrect_value_ch calls write_error
alloc_status calls write_error
invert_symmetric_matrix_sp calls write_error
read_and_validate_lambda calls write_error
incorrect_value_dp calls write_error
check_namelist_input calls write_error, incorrect_value
check_number_of_channels calls write_error
fill_symmetric_matrix_int32 calls write_error
fill_symmetric_matrix_sp calls write_error
file_io_status calls write_error
update_body_fixed_channels_info calls write_error
wavevector_squared_from_energy calls write_error
incorrect_value_sp calls write_error
prepare_wavevector_array calls write_error, wavevector_squared_from_energy
fill_symmetric_matrix_dp calls write_error
handle_lambda_index_error calls write_error
spline calls write_error
incorrect_value_int32 calls write_error
modified_bessel_temme_algorithm calls write_error
set_space_fixed_channels calls write_error
invert_symmetric_matrix_int32 calls write_error
handle_coupling_index_error calls write_error
write_header calls write_error, incorrect_value
invert_symmetric_matrix_dp calls write_error
set_number_of_channels calls check_number_of_channels
save_partial_xs_file_header calls file_io_status
calculate_single_pes_matrix_element calls wavevector_squared_from_energy, get_radial_coupling_term_value
save_open_basis_levels calls wavevector_squared_from_energy
print_channels calls wavevector_squared_from_energy
interpolate_radial_coupling_terms calls spline
read_radial_coupling_terms calls validate_r_range, read_and_validate_lambda, file_io_status
read_input_file calls check_namelist_input, file_io_status, check_namelist_basis, check_namelist_potential
save_s_matrix_file_header calls file_io_status
incorrect_value calls incorrect_value_ch, incorrect_value_dp, incorrect_value_sp, incorrect_value_int32
set_body_fixed_channels calls update_body_fixed_channels_info
calculate_k_matrix calls wavevector_squared_from_energy, modified_bessel_k_ratio
calculate_largest_wavevector calls wavevector_squared_from_energy
scattering calls prepare_wavevector_array, set_space_fixed_channels, write_header, set_number_of_channels, save_partial_xs_file_header, save_open_basis_levels, print_channels, interpolate_radial_coupling_terms, read_radial_coupling_terms, read_input_file, save_s_matrix_file_header, set_body_fixed_channels, calculate_k_matrix, calculate_largest_wavevector
get_radial_coupling_term_value calls handle_lambda_index_error, handle_coupling_index_error
modified_bessel_k_ratio calls modified_bessel_temme_algorithm
calculate_pes_matrix calls calculate_single_pes_matrix_element
check_namelist_basis calls incorrect_value
check_namelist_potential calls incorrect_value
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix
numerov calls initial_setup, general_propagation_step
handle_final_propagation_steps calls general_propagation_step