write_warning – the SCATTERING code
write_warning Subroutine
5 statements
Source File
public subroutine write_warning(message_, unit_)
writes a warning message on a chosen unit
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: message_
a message to be written
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
Calls
Called by
Contents
Source Code
write_warning
Source Code
      subroutine write_warning(message_, unit_)
         !! writes a warning message on a chosen unit
         !---------------------------------------------------------------------!
         character(len = *), intent(in)       :: message_
            !! a message to be written
         integer(int32), optional, intent(in) :: unit_
            !! optional, unit where the message will be written
         !---------------------------------------------------------------------!
         call write_message('Warning: '//trim(message_), unit_)
         !---------------------------------------------------------------------!
      end subroutine write_warning
Call graph
write_warning calls write_message
ispline calls write_warning
handle_unitarity_output_message calls write_warning
riccati_bessel_y calls write_warning
riccati_bessel_j calls write_warning
get_radial_coupling_term_value calls ispline
unitarity_check calls handle_unitarity_output_message
calculate_k_matrix calls riccati_bessel_y, riccati_bessel_j
calculate_single_pes_matrix_element calls get_radial_coupling_term_value
scattering calls unitarity_check, calculate_k_matrix
calculate_pes_matrix calls calculate_single_pes_matrix_element
initial_setup calls calculate_pes_matrix
general_propagation_step calls calculate_pes_matrix