zero_projections_3j_condition – the SCATTERING code
zero_projections_3j_condition Function
5 statements
Source File
public function zero_projections_3j_condition(x, y, z) result(is_valid)
checks the condition for nonvanishing 3-j symbol with zero projections: triangle inequality on x,y,z and if the sum x+y+z is an even integer
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: x
variables to check for 3-j symbol conditions
integer(kind=int32), intent(in) :: y
variables to check for 3-j symbol conditions
integer(kind=int32), intent(in) :: z
variables to check for 3-j symbol conditions
Return Value logical
(out) result: true/false if conditions are met
Calls
Called by
Contents
Source Code
zero_projections_3j_condition
Source Code
      function zero_projections_3j_condition(x, y, z) result(is_valid)
         !! checks the condition for nonvanishing 3-j symbol with zero projections:
         !! triangle inequality on x,y,z and if the sum x+y+z is an even integer
         !---------------------------------------------------------------------!
         integer(int32), intent(in) :: x, y, z
            !! variables to check for 3-j symbol conditions
         logical :: is_valid
            !! (out) result: true/false if conditions are met
         !---------------------------------------------------------------------!
         is_valid = (triangle_inequality_holds(x, y, z) .and. is_sum_even(x, y, z))
         !---------------------------------------------------------------------!
      end function zero_projections_3j_condition
Call graph
zero_projections_3j_condition calls triangle_inequality_holds, is_sum_even
check_nonzero_pes_matrix_elements calls zero_projections_3j_condition
process_single_matrix_element calls zero_projections_3j_condition
initialize_pes_matrix calls check_nonzero_pes_matrix_elements, prepare_pes_matrix_elements
prepare_pes_matrix_elements calls process_single_matrix_element
scattering calls initialize_pes_matrix