allocate_1d – the SCATTERING code
allocate_1d Interface
14 statements
Source File
public interface allocate_1d
Called by
Contents
Subroutines
allocate_1d_dp allocate_1d_int32 allocate_1d_sp
Subroutines
public pure module subroutine allocate_1d_dp(array_, size_)
allocate a 1d array and fill it with 0s (double precision version)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout), allocatable :: array_(:)
integer(kind=int32), intent(in) :: size_
public pure module subroutine allocate_1d_int32(array_, size_)
allocate a 1d array and fill it with 0s (integer version)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout), allocatable :: array_(:)
integer(kind=int32), intent(in) :: size_
public pure module subroutine allocate_1d_sp(array_, size_)
allocate a 1d array and fill it with 0s (single precision version)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout), allocatable :: array_(:)
integer(kind=int32), intent(in) :: size_
Call graph
initialize_pes_matrix calls allocate_1d
initialize_cross_section_arrays calls allocate_1d
read_input_file calls allocate_1d
scattering calls allocate_1d, initialize_pes_matrix, initialize_cross_section_arrays, read_input_file, save_open_basis_levels
save_open_basis_levels calls allocate_1d