fill_symmetric_matrix – the SCATTERING code
fill_symmetric_matrix Interface
14 statements
Source File
public interface fill_symmetric_matrix
Called by
Contents
Subroutines
fill_symmetric_matrix_dp fill_symmetric_matrix_int32 fill_symmetric_matrix_sp
Subroutines
public module subroutine fill_symmetric_matrix_dp(matrix_, upper_lower_)
fill the upper/lower triangle of a symmetric matrix (double precision version)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: matrix_(:,:)
character(len=1), intent(in) :: upper_lower_
public module subroutine fill_symmetric_matrix_int32(matrix_, upper_lower_)
fill the upper/lower triangle of a symmetric matrix (integer version)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: matrix_(:,:)
character(len=1), intent(in) :: upper_lower_
public module subroutine fill_symmetric_matrix_sp(matrix_, upper_lower_)
fill the upper/lower triangle of a symmetric matrix (single precision version)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: matrix_(:,:)
character(len=1), intent(in) :: upper_lower_
Call graph
calculate_pes_matrix calls fill_symmetric_matrix
calculate_s_matrix calls fill_symmetric_matrix
calculate_u_matrix calls fill_symmetric_matrix
calculate_centrifugal_matrix calls fill_symmetric_matrix
general_propagation_step calls fill_symmetric_matrix, calculate_pes_matrix, calculate_u_matrix
calculate_log_der_matrix calls fill_symmetric_matrix
initial_setup calls calculate_pes_matrix, calculate_u_matrix, calculate_centrifugal_matrix
handle_final_propagation_steps calls general_propagation_step
numerov calls general_propagation_step, calculate_log_der_matrix, initial_setup, handle_final_propagation_steps
scattering calls calculate_s_matrix, numerov