incorrect_value – the SCATTERING code
incorrect_value Interface
6 statements
Source File
public interface incorrect_value
interface for the following message: incorrect value encountered: variable_name = variable_value
Called by
Contents
Module Procedures
incorrect_value_ch incorrect_value_int32 incorrect_value_sp incorrect_value_dp
Module Procedures
private subroutine incorrect_value_ch(name_, value_, unit_)
incorrect value encountered: variable_name = variable_value
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_
name of the variable
character(len=*), intent(in) :: value_
value of the variable
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
private subroutine incorrect_value_int32(name_, value_, unit_)
incorrect value encountered: variable_name = variable_value
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_
name of the variable
integer(kind=int32), intent(in) :: value_
value of the variable
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
private subroutine incorrect_value_sp(name_, value_, unit_)
incorrect value encountered: variable_name = variable_value
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_
name of the variable
real(kind=sp), intent(in) :: value_
value of the variable
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
private subroutine incorrect_value_dp(name_, value_, unit_)
incorrect value encountered: variable_name = variable_value
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: name_
name of the variable
real(kind=dp), intent(in) :: value_
value of the variable
integer(kind=int32), intent(in), optional :: unit_
optional, unit where the message will be written
Call graph
check_namelist_input calls incorrect_value
check_namelist_basis calls incorrect_value
check_namelist_potential calls incorrect_value
write_header calls incorrect_value
read_input_file calls check_namelist_input, check_namelist_basis, check_namelist_potential
unitarity_check calls write_header
scattering calls write_header, read_input_file, unitarity_check