invert_symmetric_matrix – the SCATTERING code
invert_symmetric_matrix Interface
11 statements
Source File
public interface invert_symmetric_matrix
Called by
Contents
Subroutines
invert_symmetric_matrix_dp invert_symmetric_matrix_int32 invert_symmetric_matrix_sp
Subroutines
public module subroutine invert_symmetric_matrix_dp(matrix_)
invert a symmetric matrix using DSYTRI method (double precision version)
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: matrix_(:,:)
public module subroutine invert_symmetric_matrix_int32(matrix_)
invert a symmetric matrix using DSYTRI method (integer version)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: matrix_(:,:)
public module subroutine invert_symmetric_matrix_sp(matrix_)
invert a symmetric matrix using DSYTRI method (single precision version)
Arguments
Type Intent Optional Attributes Name
real(kind=sp), intent(inout) :: matrix_(:,:)
Call graph
calculate_s_matrix calls invert_symmetric_matrix
calculate_log_der_matrix calls invert_symmetric_matrix
general_propagation_step calls invert_symmetric_matrix, calculate_u_matrix
calculate_u_matrix calls invert_symmetric_matrix
scattering calls calculate_s_matrix, numerov
handle_final_propagation_steps calls general_propagation_step
numerov calls calculate_log_der_matrix, general_propagation_step, handle_final_propagation_steps, initial_setup
initial_setup calls calculate_u_matrix